//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFocus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Operations
    {
        public long id { get; set; }
        public Nullable<long> NumSlave { get; set; }
        public long DateTime { get; set; }
        public long FPNumber { get; set; }
        public int Operation { get; set; }
        public Nullable<bool> InWork { get; set; }
        public bool Closed { get; set; }
        public Nullable<bool> Error { get; set; }
        public Nullable<int> ByteStatus { get; set; }
        public Nullable<int> ByteResult { get; set; }
        public Nullable<int> ByteReserv { get; set; }
        public Nullable<System.DateTime> CurentDateTime { get; set; }
        public Nullable<bool> Disable { get; set; }
        public Nullable<System.DateTime> DateTimeCreate { get; set; }
        public int ErrorCounter { get; set; }
    }
}
