//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFocus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SyncDBStatus
    {
        public long id { get; set; }
        public string CompName { get; set; }
        public Nullable<long> FPNumber { get; set; }
        public string DataServer { get; set; }
        public string DataBaseName { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DateTimeSyncDB { get; set; }
    }
}
