//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFocus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Payment()
        {
            this.tbl_SALES = new HashSet<tbl_SALES>();
        }
    
        public long id { get; set; }
        public long NumOperation { get; set; }
        public long DATETIME { get; set; }
        public long FPNumber { get; set; }
        public int Operation { get; set; }
        public int SESSID { get; set; }
        public long SYSTEMID { get; set; }
        public int SAREAID { get; set; }
        public int Type { get; set; }
        public string FRECNUM { get; set; }
        public long SRECNUM { get; set; }
        public int Payment_Status { get; set; }
        public int Payment { get; set; }
        public int Payment0 { get; set; }
        public int Payment1 { get; set; }
        public int Payment2 { get; set; }
        public int Payment3 { get; set; }
        public int Payment4 { get; set; }
        public int Payment5 { get; set; }
        public int Payment6 { get; set; }
        public int Payment7 { get; set; }
        public bool CheckClose { get; set; }
        public bool FiscStatus { get; set; }
        public string CommentUp { get; set; }
        public string Comment { get; set; }
        public Nullable<int> Old_Payment { get; set; }
        public Nullable<bool> Error { get; set; }
        public Nullable<int> ByteStatus { get; set; }
        public Nullable<int> ByteResult { get; set; }
        public Nullable<int> ByteReserv { get; set; }
        public Nullable<int> FPSumm { get; set; }
        public Nullable<int> CheckSum { get; set; }
        public Nullable<int> PayBonus { get; set; }
        public Nullable<int> BousInAcc { get; set; }
        public Nullable<int> BonusCalc { get; set; }
        public Nullable<long> Card { get; set; }
        public Nullable<bool> ForWork { get; set; }
        public Nullable<int> RowCount { get; set; }
        public Nullable<bool> Disable { get; set; }
        public Nullable<int> Discount { get; set; }
        public string DiscountComment { get; set; }
        public Nullable<bool> GiftCard { get; set; }
        public Nullable<int> GiftSum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_SALES> tbl_SALES { get; set; }
    }
}
