//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFocus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SALES
    {
        public long id { get; set; }
        public Nullable<long> NumPayment { get; set; }
        public long DATETIME { get; set; }
        public long FPNumber { get; set; }
        public int SESSID { get; set; }
        public long SYSTEMID { get; set; }
        public int SAREAID { get; set; }
        public long SORT { get; set; }
        public int Type { get; set; }
        public string FRECNUM { get; set; }
        public long SRECNUM { get; set; }
        public int Amount { get; set; }
        public int Amount_Status { get; set; }
        public bool IsOneQuant { get; set; }
        public int Price { get; set; }
        public int NalogGroup { get; set; }
        public bool MemoryGoodName { get; set; }
        public string GoodName { get; set; }
        public string CommentUp { get; set; }
        public string CommentDown { get; set; }
        public string StrCode { get; set; }
        public Nullable<bool> Error { get; set; }
        public Nullable<int> ByteStatus { get; set; }
        public Nullable<int> ByteResult { get; set; }
        public Nullable<int> ByteReserv { get; set; }
        public Nullable<int> Old_Price { get; set; }
        public Nullable<long> packname { get; set; }
        public Nullable<System.Guid> PackGuid { get; set; }
        public Nullable<int> RowSum { get; set; }
        public Nullable<int> FPSum { get; set; }
        public Nullable<bool> ForWork { get; set; }
        public Nullable<int> discount { get; set; }
        public Nullable<bool> exchange { get; set; }
        public string DiscountComment { get; set; }
    
        public virtual tbl_Payment tbl_Payment { get; set; }
    }
}
