//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFocus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Names
    {
        public long id { get; set; }
        public long FPNumber { get; set; }
        public string Name { get; set; }
        public int idFirm { get; set; }
        public int idObject { get; set; }
    }
}
