//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFocus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Log
    {
        public long id { get; set; }
        public string ServerName { get; set; }
        public string SQLserver { get; set; }
        public string FPNumber { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public Nullable<long> DateTimeStamp { get; set; }
        public string Loglevel { get; set; }
        public string Logger { get; set; }
        public string Callsite { get; set; }
        public string Message { get; set; }
        public Nullable<int> TimeSpan { get; set; }
        public Nullable<bool> SkypeInfo { get; set; }
        public Nullable<long> FPNumberInt { get; set; }
    }
}
