#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncOpenStore
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CashDesk_OS")]
	public partial class DataClassesOSDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSESS(SESS instance);
    partial void UpdateSESS(SESS instance);
    partial void DeleteSESS(SESS instance);
    partial void InsertCASHIER(CASHIER instance);
    partial void UpdateCASHIER(CASHIER instance);
    partial void DeleteCASHIER(CASHIER instance);
    partial void InsertSALE(SALE instance);
    partial void UpdateSALE(SALE instance);
    partial void DeleteSALE(SALE instance);
    partial void InsertWORKDAY(WORKDAY instance);
    partial void UpdateWORKDAY(WORKDAY instance);
    partial void DeleteWORKDAY(WORKDAY instance);
    partial void InsertZREP(ZREP instance);
    partial void UpdateZREP(ZREP instance);
    partial void DeleteZREP(ZREP instance);
    partial void InsertCASHIO(CASHIO instance);
    partial void UpdateCASHIO(CASHIO instance);
    partial void DeleteCASHIO(CASHIO instance);
    partial void InsertDCARD(DCARD instance);
    partial void UpdateDCARD(DCARD instance);
    partial void DeleteDCARD(DCARD instance);
    #endregion
		
		public DataClassesOSDataContext() : 
				base(global::SyncOpenStore.Properties.Settings.Default.CashDesk_OSConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesOSDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesOSDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesOSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesOSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<SESS> SESSes
		{
			get
			{
				return this.GetTable<SESS>();
			}
		}
		
		public System.Data.Linq.Table<CASHIER> CASHIERs
		{
			get
			{
				return this.GetTable<CASHIER>();
			}
		}
		
		public System.Data.Linq.Table<SALE> SALEs
		{
			get
			{
				return this.GetTable<SALE>();
			}
		}
		
		public System.Data.Linq.Table<WORKDAY> WORKDAYs
		{
			get
			{
				return this.GetTable<WORKDAY>();
			}
		}
		
		public System.Data.Linq.Table<ZREP> ZREPs
		{
			get
			{
				return this.GetTable<ZREP>();
			}
		}
		
		public System.Data.Linq.Table<CASHIO> CASHIOs
		{
			get
			{
				return this.GetTable<CASHIO>();
			}
		}
		
		public System.Data.Linq.Table<DCARD> DCARDs
		{
			get
			{
				return this.GetTable<DCARD>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SESS")]
	public partial class SESS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SESSID;
		
		private int _SYSTEMID;
		
		private int _SAREAID;
		
		private System.Nullable<int> _WORKDAYID;
		
		private string _SESSSTART;
		
		private decimal _SESSCASHIN;
		
		private decimal _SESSCASHINIT;
		
		private int _CASHIERID;
		
		private short _DELFLAG;
		
		private int _UPDATENUM;
		
		private int _UPDATENUM2;
		
		private EntitySet<CASHIO> _CASHIOs;
		
		private EntityRef<WORKDAY> _WORKDAY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSESSIDChanging(int value);
    partial void OnSESSIDChanged();
    partial void OnSYSTEMIDChanging(int value);
    partial void OnSYSTEMIDChanged();
    partial void OnSAREAIDChanging(int value);
    partial void OnSAREAIDChanged();
    partial void OnWORKDAYIDChanging(System.Nullable<int> value);
    partial void OnWORKDAYIDChanged();
    partial void OnSESSSTARTChanging(string value);
    partial void OnSESSSTARTChanged();
    partial void OnSESSCASHINChanging(decimal value);
    partial void OnSESSCASHINChanged();
    partial void OnSESSCASHINITChanging(decimal value);
    partial void OnSESSCASHINITChanged();
    partial void OnCASHIERIDChanging(int value);
    partial void OnCASHIERIDChanged();
    partial void OnDELFLAGChanging(short value);
    partial void OnDELFLAGChanged();
    partial void OnUPDATENUMChanging(int value);
    partial void OnUPDATENUMChanged();
    partial void OnUPDATENUM2Changing(int value);
    partial void OnUPDATENUM2Changed();
    #endregion
		
		public SESS()
		{
			this._CASHIOs = new EntitySet<CASHIO>(new Action<CASHIO>(this.attach_CASHIOs), new Action<CASHIO>(this.detach_CASHIOs));
			this._WORKDAY = default(EntityRef<WORKDAY>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SESSID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SESSID
		{
			get
			{
				return this._SESSID;
			}
			set
			{
				if ((this._SESSID != value))
				{
					this.OnSESSIDChanging(value);
					this.SendPropertyChanging();
					this._SESSID = value;
					this.SendPropertyChanged("SESSID");
					this.OnSESSIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SYSTEMID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SYSTEMID
		{
			get
			{
				return this._SYSTEMID;
			}
			set
			{
				if ((this._SYSTEMID != value))
				{
					if (this._WORKDAY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSYSTEMIDChanging(value);
					this.SendPropertyChanging();
					this._SYSTEMID = value;
					this.SendPropertyChanged("SYSTEMID");
					this.OnSYSTEMIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAREAID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SAREAID
		{
			get
			{
				return this._SAREAID;
			}
			set
			{
				if ((this._SAREAID != value))
				{
					if (this._WORKDAY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSAREAIDChanging(value);
					this.SendPropertyChanging();
					this._SAREAID = value;
					this.SendPropertyChanged("SAREAID");
					this.OnSAREAIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WORKDAYID", DbType="Int")]
		public System.Nullable<int> WORKDAYID
		{
			get
			{
				return this._WORKDAYID;
			}
			set
			{
				if ((this._WORKDAYID != value))
				{
					if (this._WORKDAY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnWORKDAYIDChanging(value);
					this.SendPropertyChanging();
					this._WORKDAYID = value;
					this.SendPropertyChanged("WORKDAYID");
					this.OnWORKDAYIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SESSSTART", DbType="VarChar(14) NOT NULL", CanBeNull=false)]
		public string SESSSTART
		{
			get
			{
				return this._SESSSTART;
			}
			set
			{
				if ((this._SESSSTART != value))
				{
					this.OnSESSSTARTChanging(value);
					this.SendPropertyChanging();
					this._SESSSTART = value;
					this.SendPropertyChanged("SESSSTART");
					this.OnSESSSTARTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SESSCASHIN", DbType="Decimal(18,6) NOT NULL")]
		public decimal SESSCASHIN
		{
			get
			{
				return this._SESSCASHIN;
			}
			set
			{
				if ((this._SESSCASHIN != value))
				{
					this.OnSESSCASHINChanging(value);
					this.SendPropertyChanging();
					this._SESSCASHIN = value;
					this.SendPropertyChanged("SESSCASHIN");
					this.OnSESSCASHINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SESSCASHINIT", DbType="Decimal(18,6) NOT NULL")]
		public decimal SESSCASHINIT
		{
			get
			{
				return this._SESSCASHINIT;
			}
			set
			{
				if ((this._SESSCASHINIT != value))
				{
					this.OnSESSCASHINITChanging(value);
					this.SendPropertyChanging();
					this._SESSCASHINIT = value;
					this.SendPropertyChanged("SESSCASHINIT");
					this.OnSESSCASHINITChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CASHIERID", DbType="Int NOT NULL")]
		public int CASHIERID
		{
			get
			{
				return this._CASHIERID;
			}
			set
			{
				if ((this._CASHIERID != value))
				{
					this.OnCASHIERIDChanging(value);
					this.SendPropertyChanging();
					this._CASHIERID = value;
					this.SendPropertyChanged("CASHIERID");
					this.OnCASHIERIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DELFLAG", DbType="SmallInt NOT NULL")]
		public short DELFLAG
		{
			get
			{
				return this._DELFLAG;
			}
			set
			{
				if ((this._DELFLAG != value))
				{
					this.OnDELFLAGChanging(value);
					this.SendPropertyChanging();
					this._DELFLAG = value;
					this.SendPropertyChanged("DELFLAG");
					this.OnDELFLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATENUM", DbType="Int NOT NULL")]
		public int UPDATENUM
		{
			get
			{
				return this._UPDATENUM;
			}
			set
			{
				if ((this._UPDATENUM != value))
				{
					this.OnUPDATENUMChanging(value);
					this.SendPropertyChanging();
					this._UPDATENUM = value;
					this.SendPropertyChanged("UPDATENUM");
					this.OnUPDATENUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATENUM2", DbType="Int NOT NULL")]
		public int UPDATENUM2
		{
			get
			{
				return this._UPDATENUM2;
			}
			set
			{
				if ((this._UPDATENUM2 != value))
				{
					this.OnUPDATENUM2Changing(value);
					this.SendPropertyChanging();
					this._UPDATENUM2 = value;
					this.SendPropertyChanged("UPDATENUM2");
					this.OnUPDATENUM2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SESS_CASHIO", Storage="_CASHIOs", ThisKey="SESSID,SYSTEMID,SAREAID", OtherKey="SESSID,SYSTEMID,SAREAID")]
		public EntitySet<CASHIO> CASHIOs
		{
			get
			{
				return this._CASHIOs;
			}
			set
			{
				this._CASHIOs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="WORKDAY_SESS", Storage="_WORKDAY", ThisKey="WORKDAYID,SYSTEMID,SAREAID", OtherKey="WORKDAYID,SYSTEMID,SAREAID", IsForeignKey=true)]
		public WORKDAY WORKDAY
		{
			get
			{
				return this._WORKDAY.Entity;
			}
			set
			{
				WORKDAY previousValue = this._WORKDAY.Entity;
				if (((previousValue != value) 
							|| (this._WORKDAY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._WORKDAY.Entity = null;
						previousValue.SESSes.Remove(this);
					}
					this._WORKDAY.Entity = value;
					if ((value != null))
					{
						value.SESSes.Add(this);
						this._WORKDAYID = value.WORKDAYID;
						this._SYSTEMID = value.SYSTEMID;
						this._SAREAID = value.SAREAID;
					}
					else
					{
						this._WORKDAYID = default(Nullable<int>);
						this._SYSTEMID = default(int);
						this._SAREAID = default(int);
					}
					this.SendPropertyChanged("WORKDAY");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CASHIOs(CASHIO entity)
		{
			this.SendPropertyChanging();
			entity.SESS = this;
		}
		
		private void detach_CASHIOs(CASHIO entity)
		{
			this.SendPropertyChanging();
			entity.SESS = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CASHIER")]
	public partial class CASHIER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CASHIERID;
		
		private int _CASHIERGRPID;
		
		private string _CASHIERKEY;
		
		private string _CASHIERPASSWORD;
		
		private string _CASHIERNAME;
		
		private short _CASHIERDISABLED;
		
		private short _CASHIERSAREACONTROL;
		
		private short _DELFLAG;
		
		private int _UPDATENUM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCASHIERIDChanging(int value);
    partial void OnCASHIERIDChanged();
    partial void OnCASHIERGRPIDChanging(int value);
    partial void OnCASHIERGRPIDChanged();
    partial void OnCASHIERKEYChanging(string value);
    partial void OnCASHIERKEYChanged();
    partial void OnCASHIERPASSWORDChanging(string value);
    partial void OnCASHIERPASSWORDChanged();
    partial void OnCASHIERNAMEChanging(string value);
    partial void OnCASHIERNAMEChanged();
    partial void OnCASHIERDISABLEDChanging(short value);
    partial void OnCASHIERDISABLEDChanged();
    partial void OnCASHIERSAREACONTROLChanging(short value);
    partial void OnCASHIERSAREACONTROLChanged();
    partial void OnDELFLAGChanging(short value);
    partial void OnDELFLAGChanged();
    partial void OnUPDATENUMChanging(int value);
    partial void OnUPDATENUMChanged();
    #endregion
		
		public CASHIER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CASHIERID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CASHIERID
		{
			get
			{
				return this._CASHIERID;
			}
			set
			{
				if ((this._CASHIERID != value))
				{
					this.OnCASHIERIDChanging(value);
					this.SendPropertyChanging();
					this._CASHIERID = value;
					this.SendPropertyChanged("CASHIERID");
					this.OnCASHIERIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CASHIERGRPID", DbType="Int NOT NULL")]
		public int CASHIERGRPID
		{
			get
			{
				return this._CASHIERGRPID;
			}
			set
			{
				if ((this._CASHIERGRPID != value))
				{
					this.OnCASHIERGRPIDChanging(value);
					this.SendPropertyChanging();
					this._CASHIERGRPID = value;
					this.SendPropertyChanged("CASHIERGRPID");
					this.OnCASHIERGRPIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CASHIERKEY", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CASHIERKEY
		{
			get
			{
				return this._CASHIERKEY;
			}
			set
			{
				if ((this._CASHIERKEY != value))
				{
					this.OnCASHIERKEYChanging(value);
					this.SendPropertyChanging();
					this._CASHIERKEY = value;
					this.SendPropertyChanged("CASHIERKEY");
					this.OnCASHIERKEYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CASHIERPASSWORD", DbType="NVarChar(30)")]
		public string CASHIERPASSWORD
		{
			get
			{
				return this._CASHIERPASSWORD;
			}
			set
			{
				if ((this._CASHIERPASSWORD != value))
				{
					this.OnCASHIERPASSWORDChanging(value);
					this.SendPropertyChanging();
					this._CASHIERPASSWORD = value;
					this.SendPropertyChanged("CASHIERPASSWORD");
					this.OnCASHIERPASSWORDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CASHIERNAME", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CASHIERNAME
		{
			get
			{
				return this._CASHIERNAME;
			}
			set
			{
				if ((this._CASHIERNAME != value))
				{
					this.OnCASHIERNAMEChanging(value);
					this.SendPropertyChanging();
					this._CASHIERNAME = value;
					this.SendPropertyChanged("CASHIERNAME");
					this.OnCASHIERNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CASHIERDISABLED", DbType="SmallInt NOT NULL")]
		public short CASHIERDISABLED
		{
			get
			{
				return this._CASHIERDISABLED;
			}
			set
			{
				if ((this._CASHIERDISABLED != value))
				{
					this.OnCASHIERDISABLEDChanging(value);
					this.SendPropertyChanging();
					this._CASHIERDISABLED = value;
					this.SendPropertyChanged("CASHIERDISABLED");
					this.OnCASHIERDISABLEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CASHIERSAREACONTROL", DbType="SmallInt NOT NULL")]
		public short CASHIERSAREACONTROL
		{
			get
			{
				return this._CASHIERSAREACONTROL;
			}
			set
			{
				if ((this._CASHIERSAREACONTROL != value))
				{
					this.OnCASHIERSAREACONTROLChanging(value);
					this.SendPropertyChanging();
					this._CASHIERSAREACONTROL = value;
					this.SendPropertyChanged("CASHIERSAREACONTROL");
					this.OnCASHIERSAREACONTROLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DELFLAG", DbType="SmallInt NOT NULL")]
		public short DELFLAG
		{
			get
			{
				return this._DELFLAG;
			}
			set
			{
				if ((this._DELFLAG != value))
				{
					this.OnDELFLAGChanging(value);
					this.SendPropertyChanging();
					this._DELFLAG = value;
					this.SendPropertyChanged("DELFLAG");
					this.OnDELFLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATENUM", DbType="Int NOT NULL")]
		public int UPDATENUM
		{
			get
			{
				return this._UPDATENUM;
			}
			set
			{
				if ((this._UPDATENUM != value))
				{
					this.OnUPDATENUMChanging(value);
					this.SendPropertyChanging();
					this._UPDATENUM = value;
					this.SendPropertyChanged("UPDATENUM");
					this.OnUPDATENUMChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SALES")]
	public partial class SALE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SALESNUM;
		
		private int _SESSID;
		
		private int _PRCLEVELID;
		
		private int _SYSTEMID;
		
		private System.Nullable<int> _TXTBINID;
		
		private int _SAREAID;
		
		private int _SALESTAG;
		
		private string _SALESTIME;
		
		private string _FRECNUM;
		
		private int _SRECNUM;
		
		private string _SALESBARC;
		
		private System.Nullable<decimal> _SALESDISC;
		
		private System.Nullable<decimal> _SALESPRICE;
		
		private System.Nullable<decimal> _SALESSUM;
		
		private System.Nullable<decimal> _BONUSSUM;
		
		private System.Nullable<int> _SALESCOUNT;
		
		private System.Nullable<int> _SALESCODE;
		
		private System.Nullable<int> _SALESTYPE;
		
		private short _SALESCANC;
		
		private System.Nullable<int> _SALESFLAGS;
		
		private int _SALESREFUND;
		
		private System.Nullable<int> _ARTID;
		
		private string _PACKNAME;
		
		private System.Nullable<int> _PACKID;
		
		private System.Nullable<int> _PACKCOUNT;
		
		private int _CASHIERID;
		
		private System.Nullable<int> _SALESATTRI;
		
		private string _SALESATTRS;
		
		private int _SALESEXTCOUNT;
		
		private short _DELFLAG;
		
		private System.Nullable<int> _CLNTID;
		
		private System.Nullable<decimal> _SALESBONUS;
		
		private int _SYSTEMTYPE;
		
		private int _UPDATENUM;
		
		private System.Nullable<int> _UPDATENUM2;
		
		private System.Nullable<int> _FIRMID;
		
		private System.Nullable<int> _ParentSRecNum;
		
		private System.Nullable<int> _CURRENCYID;
		
		private System.Nullable<decimal> _CURRENCYRATE;
		
		private System.Nullable<decimal> _CURRENCYSALESSUM;
		
		private System.Nullable<int> _DISCPOLICYID;
		
		private System.Nullable<int> _BONUSPOLICYID;
		
		private System.Nullable<int> _OFFERIDFORBONUS;
		
		private System.Nullable<int> _OFFERIDFORDISC;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSALESNUMChanging(int value);
    partial void OnSALESNUMChanged();
    partial void OnSESSIDChanging(int value);
    partial void OnSESSIDChanged();
    partial void OnPRCLEVELIDChanging(int value);
    partial void OnPRCLEVELIDChanged();
    partial void OnSYSTEMIDChanging(int value);
    partial void OnSYSTEMIDChanged();
    partial void OnTXTBINIDChanging(System.Nullable<int> value);
    partial void OnTXTBINIDChanged();
    partial void OnSAREAIDChanging(int value);
    partial void OnSAREAIDChanged();
    partial void OnSALESTAGChanging(int value);
    partial void OnSALESTAGChanged();
    partial void OnSALESTIMEChanging(string value);
    partial void OnSALESTIMEChanged();
    partial void OnFRECNUMChanging(string value);
    partial void OnFRECNUMChanged();
    partial void OnSRECNUMChanging(int value);
    partial void OnSRECNUMChanged();
    partial void OnSALESBARCChanging(string value);
    partial void OnSALESBARCChanged();
    partial void OnSALESDISCChanging(System.Nullable<decimal> value);
    partial void OnSALESDISCChanged();
    partial void OnSALESPRICEChanging(System.Nullable<decimal> value);
    partial void OnSALESPRICEChanged();
    partial void OnSALESSUMChanging(System.Nullable<decimal> value);
    partial void OnSALESSUMChanged();
    partial void OnBONUSSUMChanging(System.Nullable<decimal> value);
    partial void OnBONUSSUMChanged();
    partial void OnSALESCOUNTChanging(System.Nullable<int> value);
    partial void OnSALESCOUNTChanged();
    partial void OnSALESCODEChanging(System.Nullable<int> value);
    partial void OnSALESCODEChanged();
    partial void OnSALESTYPEChanging(System.Nullable<int> value);
    partial void OnSALESTYPEChanged();
    partial void OnSALESCANCChanging(short value);
    partial void OnSALESCANCChanged();
    partial void OnSALESFLAGSChanging(System.Nullable<int> value);
    partial void OnSALESFLAGSChanged();
    partial void OnSALESREFUNDChanging(int value);
    partial void OnSALESREFUNDChanged();
    partial void OnARTIDChanging(System.Nullable<int> value);
    partial void OnARTIDChanged();
    partial void OnPACKNAMEChanging(string value);
    partial void OnPACKNAMEChanged();
    partial void OnPACKIDChanging(System.Nullable<int> value);
    partial void OnPACKIDChanged();
    partial void OnPACKCOUNTChanging(System.Nullable<int> value);
    partial void OnPACKCOUNTChanged();
    partial void OnCASHIERIDChanging(int value);
    partial void OnCASHIERIDChanged();
    partial void OnSALESATTRIChanging(System.Nullable<int> value);
    partial void OnSALESATTRIChanged();
    partial void OnSALESATTRSChanging(string value);
    partial void OnSALESATTRSChanged();
    partial void OnSALESEXTCOUNTChanging(int value);
    partial void OnSALESEXTCOUNTChanged();
    partial void OnDELFLAGChanging(short value);
    partial void OnDELFLAGChanged();
    partial void OnCLNTIDChanging(System.Nullable<int> value);
    partial void OnCLNTIDChanged();
    partial void OnSALESBONUSChanging(System.Nullable<decimal> value);
    partial void OnSALESBONUSChanged();
    partial void OnSYSTEMTYPEChanging(int value);
    partial void OnSYSTEMTYPEChanged();
    partial void OnUPDATENUMChanging(int value);
    partial void OnUPDATENUMChanged();
    partial void OnUPDATENUM2Changing(System.Nullable<int> value);
    partial void OnUPDATENUM2Changed();
    partial void OnFIRMIDChanging(System.Nullable<int> value);
    partial void OnFIRMIDChanged();
    partial void OnParentSRecNumChanging(System.Nullable<int> value);
    partial void OnParentSRecNumChanged();
    partial void OnCURRENCYIDChanging(System.Nullable<int> value);
    partial void OnCURRENCYIDChanged();
    partial void OnCURRENCYRATEChanging(System.Nullable<decimal> value);
    partial void OnCURRENCYRATEChanged();
    partial void OnCURRENCYSALESSUMChanging(System.Nullable<decimal> value);
    partial void OnCURRENCYSALESSUMChanged();
    partial void OnDISCPOLICYIDChanging(System.Nullable<int> value);
    partial void OnDISCPOLICYIDChanged();
    partial void OnBONUSPOLICYIDChanging(System.Nullable<int> value);
    partial void OnBONUSPOLICYIDChanged();
    partial void OnOFFERIDFORBONUSChanging(System.Nullable<int> value);
    partial void OnOFFERIDFORBONUSChanged();
    partial void OnOFFERIDFORDISCChanging(System.Nullable<int> value);
    partial void OnOFFERIDFORDISCChanged();
    #endregion
		
		public SALE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALESNUM", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SALESNUM
		{
			get
			{
				return this._SALESNUM;
			}
			set
			{
				if ((this._SALESNUM != value))
				{
					this.OnSALESNUMChanging(value);
					this.SendPropertyChanging();
					this._SALESNUM = value;
					this.SendPropertyChanged("SALESNUM");
					this.OnSALESNUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SESSID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SESSID
		{
			get
			{
				return this._SESSID;
			}
			set
			{
				if ((this._SESSID != value))
				{
					this.OnSESSIDChanging(value);
					this.SendPropertyChanging();
					this._SESSID = value;
					this.SendPropertyChanged("SESSID");
					this.OnSESSIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRCLEVELID", DbType="Int NOT NULL")]
		public int PRCLEVELID
		{
			get
			{
				return this._PRCLEVELID;
			}
			set
			{
				if ((this._PRCLEVELID != value))
				{
					this.OnPRCLEVELIDChanging(value);
					this.SendPropertyChanging();
					this._PRCLEVELID = value;
					this.SendPropertyChanged("PRCLEVELID");
					this.OnPRCLEVELIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SYSTEMID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SYSTEMID
		{
			get
			{
				return this._SYSTEMID;
			}
			set
			{
				if ((this._SYSTEMID != value))
				{
					this.OnSYSTEMIDChanging(value);
					this.SendPropertyChanging();
					this._SYSTEMID = value;
					this.SendPropertyChanged("SYSTEMID");
					this.OnSYSTEMIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TXTBINID", DbType="Int")]
		public System.Nullable<int> TXTBINID
		{
			get
			{
				return this._TXTBINID;
			}
			set
			{
				if ((this._TXTBINID != value))
				{
					this.OnTXTBINIDChanging(value);
					this.SendPropertyChanging();
					this._TXTBINID = value;
					this.SendPropertyChanged("TXTBINID");
					this.OnTXTBINIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAREAID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SAREAID
		{
			get
			{
				return this._SAREAID;
			}
			set
			{
				if ((this._SAREAID != value))
				{
					this.OnSAREAIDChanging(value);
					this.SendPropertyChanging();
					this._SAREAID = value;
					this.SendPropertyChanged("SAREAID");
					this.OnSAREAIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALESTAG", DbType="Int NOT NULL")]
		public int SALESTAG
		{
			get
			{
				return this._SALESTAG;
			}
			set
			{
				if ((this._SALESTAG != value))
				{
					this.OnSALESTAGChanging(value);
					this.SendPropertyChanging();
					this._SALESTAG = value;
					this.SendPropertyChanged("SALESTAG");
					this.OnSALESTAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALESTIME", DbType="VarChar(14)")]
		public string SALESTIME
		{
			get
			{
				return this._SALESTIME;
			}
			set
			{
				if ((this._SALESTIME != value))
				{
					this.OnSALESTIMEChanging(value);
					this.SendPropertyChanging();
					this._SALESTIME = value;
					this.SendPropertyChanged("SALESTIME");
					this.OnSALESTIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FRECNUM", DbType="NVarChar(30)")]
		public string FRECNUM
		{
			get
			{
				return this._FRECNUM;
			}
			set
			{
				if ((this._FRECNUM != value))
				{
					this.OnFRECNUMChanging(value);
					this.SendPropertyChanging();
					this._FRECNUM = value;
					this.SendPropertyChanged("FRECNUM");
					this.OnFRECNUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SRECNUM", DbType="Int NOT NULL")]
		public int SRECNUM
		{
			get
			{
				return this._SRECNUM;
			}
			set
			{
				if ((this._SRECNUM != value))
				{
					this.OnSRECNUMChanging(value);
					this.SendPropertyChanging();
					this._SRECNUM = value;
					this.SendPropertyChanged("SRECNUM");
					this.OnSRECNUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALESBARC", DbType="NVarChar(30)")]
		public string SALESBARC
		{
			get
			{
				return this._SALESBARC;
			}
			set
			{
				if ((this._SALESBARC != value))
				{
					this.OnSALESBARCChanging(value);
					this.SendPropertyChanging();
					this._SALESBARC = value;
					this.SendPropertyChanged("SALESBARC");
					this.OnSALESBARCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALESDISC", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> SALESDISC
		{
			get
			{
				return this._SALESDISC;
			}
			set
			{
				if ((this._SALESDISC != value))
				{
					this.OnSALESDISCChanging(value);
					this.SendPropertyChanging();
					this._SALESDISC = value;
					this.SendPropertyChanged("SALESDISC");
					this.OnSALESDISCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALESPRICE", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> SALESPRICE
		{
			get
			{
				return this._SALESPRICE;
			}
			set
			{
				if ((this._SALESPRICE != value))
				{
					this.OnSALESPRICEChanging(value);
					this.SendPropertyChanging();
					this._SALESPRICE = value;
					this.SendPropertyChanged("SALESPRICE");
					this.OnSALESPRICEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALESSUM", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> SALESSUM
		{
			get
			{
				return this._SALESSUM;
			}
			set
			{
				if ((this._SALESSUM != value))
				{
					this.OnSALESSUMChanging(value);
					this.SendPropertyChanging();
					this._SALESSUM = value;
					this.SendPropertyChanged("SALESSUM");
					this.OnSALESSUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BONUSSUM", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> BONUSSUM
		{
			get
			{
				return this._BONUSSUM;
			}
			set
			{
				if ((this._BONUSSUM != value))
				{
					this.OnBONUSSUMChanging(value);
					this.SendPropertyChanging();
					this._BONUSSUM = value;
					this.SendPropertyChanged("BONUSSUM");
					this.OnBONUSSUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALESCOUNT", DbType="Int")]
		public System.Nullable<int> SALESCOUNT
		{
			get
			{
				return this._SALESCOUNT;
			}
			set
			{
				if ((this._SALESCOUNT != value))
				{
					this.OnSALESCOUNTChanging(value);
					this.SendPropertyChanging();
					this._SALESCOUNT = value;
					this.SendPropertyChanged("SALESCOUNT");
					this.OnSALESCOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALESCODE", DbType="Int")]
		public System.Nullable<int> SALESCODE
		{
			get
			{
				return this._SALESCODE;
			}
			set
			{
				if ((this._SALESCODE != value))
				{
					this.OnSALESCODEChanging(value);
					this.SendPropertyChanging();
					this._SALESCODE = value;
					this.SendPropertyChanged("SALESCODE");
					this.OnSALESCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALESTYPE", DbType="Int")]
		public System.Nullable<int> SALESTYPE
		{
			get
			{
				return this._SALESTYPE;
			}
			set
			{
				if ((this._SALESTYPE != value))
				{
					this.OnSALESTYPEChanging(value);
					this.SendPropertyChanging();
					this._SALESTYPE = value;
					this.SendPropertyChanged("SALESTYPE");
					this.OnSALESTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALESCANC", DbType="SmallInt NOT NULL")]
		public short SALESCANC
		{
			get
			{
				return this._SALESCANC;
			}
			set
			{
				if ((this._SALESCANC != value))
				{
					this.OnSALESCANCChanging(value);
					this.SendPropertyChanging();
					this._SALESCANC = value;
					this.SendPropertyChanged("SALESCANC");
					this.OnSALESCANCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALESFLAGS", DbType="Int")]
		public System.Nullable<int> SALESFLAGS
		{
			get
			{
				return this._SALESFLAGS;
			}
			set
			{
				if ((this._SALESFLAGS != value))
				{
					this.OnSALESFLAGSChanging(value);
					this.SendPropertyChanging();
					this._SALESFLAGS = value;
					this.SendPropertyChanged("SALESFLAGS");
					this.OnSALESFLAGSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALESREFUND", DbType="Int NOT NULL")]
		public int SALESREFUND
		{
			get
			{
				return this._SALESREFUND;
			}
			set
			{
				if ((this._SALESREFUND != value))
				{
					this.OnSALESREFUNDChanging(value);
					this.SendPropertyChanging();
					this._SALESREFUND = value;
					this.SendPropertyChanged("SALESREFUND");
					this.OnSALESREFUNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARTID", DbType="Int")]
		public System.Nullable<int> ARTID
		{
			get
			{
				return this._ARTID;
			}
			set
			{
				if ((this._ARTID != value))
				{
					this.OnARTIDChanging(value);
					this.SendPropertyChanging();
					this._ARTID = value;
					this.SendPropertyChanged("ARTID");
					this.OnARTIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PACKNAME", DbType="NVarChar(30)")]
		public string PACKNAME
		{
			get
			{
				return this._PACKNAME;
			}
			set
			{
				if ((this._PACKNAME != value))
				{
					this.OnPACKNAMEChanging(value);
					this.SendPropertyChanging();
					this._PACKNAME = value;
					this.SendPropertyChanged("PACKNAME");
					this.OnPACKNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PACKID", DbType="Int")]
		public System.Nullable<int> PACKID
		{
			get
			{
				return this._PACKID;
			}
			set
			{
				if ((this._PACKID != value))
				{
					this.OnPACKIDChanging(value);
					this.SendPropertyChanging();
					this._PACKID = value;
					this.SendPropertyChanged("PACKID");
					this.OnPACKIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PACKCOUNT", DbType="Int")]
		public System.Nullable<int> PACKCOUNT
		{
			get
			{
				return this._PACKCOUNT;
			}
			set
			{
				if ((this._PACKCOUNT != value))
				{
					this.OnPACKCOUNTChanging(value);
					this.SendPropertyChanging();
					this._PACKCOUNT = value;
					this.SendPropertyChanged("PACKCOUNT");
					this.OnPACKCOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CASHIERID", DbType="Int NOT NULL")]
		public int CASHIERID
		{
			get
			{
				return this._CASHIERID;
			}
			set
			{
				if ((this._CASHIERID != value))
				{
					this.OnCASHIERIDChanging(value);
					this.SendPropertyChanging();
					this._CASHIERID = value;
					this.SendPropertyChanged("CASHIERID");
					this.OnCASHIERIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALESATTRI", DbType="Int")]
		public System.Nullable<int> SALESATTRI
		{
			get
			{
				return this._SALESATTRI;
			}
			set
			{
				if ((this._SALESATTRI != value))
				{
					this.OnSALESATTRIChanging(value);
					this.SendPropertyChanging();
					this._SALESATTRI = value;
					this.SendPropertyChanged("SALESATTRI");
					this.OnSALESATTRIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALESATTRS", DbType="NVarChar(100)")]
		public string SALESATTRS
		{
			get
			{
				return this._SALESATTRS;
			}
			set
			{
				if ((this._SALESATTRS != value))
				{
					this.OnSALESATTRSChanging(value);
					this.SendPropertyChanging();
					this._SALESATTRS = value;
					this.SendPropertyChanged("SALESATTRS");
					this.OnSALESATTRSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALESEXTCOUNT", DbType="Int NOT NULL")]
		public int SALESEXTCOUNT
		{
			get
			{
				return this._SALESEXTCOUNT;
			}
			set
			{
				if ((this._SALESEXTCOUNT != value))
				{
					this.OnSALESEXTCOUNTChanging(value);
					this.SendPropertyChanging();
					this._SALESEXTCOUNT = value;
					this.SendPropertyChanged("SALESEXTCOUNT");
					this.OnSALESEXTCOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DELFLAG", DbType="SmallInt NOT NULL")]
		public short DELFLAG
		{
			get
			{
				return this._DELFLAG;
			}
			set
			{
				if ((this._DELFLAG != value))
				{
					this.OnDELFLAGChanging(value);
					this.SendPropertyChanging();
					this._DELFLAG = value;
					this.SendPropertyChanged("DELFLAG");
					this.OnDELFLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLNTID", DbType="Int")]
		public System.Nullable<int> CLNTID
		{
			get
			{
				return this._CLNTID;
			}
			set
			{
				if ((this._CLNTID != value))
				{
					this.OnCLNTIDChanging(value);
					this.SendPropertyChanging();
					this._CLNTID = value;
					this.SendPropertyChanged("CLNTID");
					this.OnCLNTIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALESBONUS", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> SALESBONUS
		{
			get
			{
				return this._SALESBONUS;
			}
			set
			{
				if ((this._SALESBONUS != value))
				{
					this.OnSALESBONUSChanging(value);
					this.SendPropertyChanging();
					this._SALESBONUS = value;
					this.SendPropertyChanged("SALESBONUS");
					this.OnSALESBONUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SYSTEMTYPE", DbType="Int NOT NULL")]
		public int SYSTEMTYPE
		{
			get
			{
				return this._SYSTEMTYPE;
			}
			set
			{
				if ((this._SYSTEMTYPE != value))
				{
					this.OnSYSTEMTYPEChanging(value);
					this.SendPropertyChanging();
					this._SYSTEMTYPE = value;
					this.SendPropertyChanged("SYSTEMTYPE");
					this.OnSYSTEMTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATENUM", DbType="Int NOT NULL")]
		public int UPDATENUM
		{
			get
			{
				return this._UPDATENUM;
			}
			set
			{
				if ((this._UPDATENUM != value))
				{
					this.OnUPDATENUMChanging(value);
					this.SendPropertyChanging();
					this._UPDATENUM = value;
					this.SendPropertyChanged("UPDATENUM");
					this.OnUPDATENUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATENUM2", DbType="Int")]
		public System.Nullable<int> UPDATENUM2
		{
			get
			{
				return this._UPDATENUM2;
			}
			set
			{
				if ((this._UPDATENUM2 != value))
				{
					this.OnUPDATENUM2Changing(value);
					this.SendPropertyChanging();
					this._UPDATENUM2 = value;
					this.SendPropertyChanged("UPDATENUM2");
					this.OnUPDATENUM2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIRMID", DbType="Int")]
		public System.Nullable<int> FIRMID
		{
			get
			{
				return this._FIRMID;
			}
			set
			{
				if ((this._FIRMID != value))
				{
					this.OnFIRMIDChanging(value);
					this.SendPropertyChanging();
					this._FIRMID = value;
					this.SendPropertyChanged("FIRMID");
					this.OnFIRMIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentSRecNum", DbType="Int")]
		public System.Nullable<int> ParentSRecNum
		{
			get
			{
				return this._ParentSRecNum;
			}
			set
			{
				if ((this._ParentSRecNum != value))
				{
					this.OnParentSRecNumChanging(value);
					this.SendPropertyChanging();
					this._ParentSRecNum = value;
					this.SendPropertyChanged("ParentSRecNum");
					this.OnParentSRecNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CURRENCYID", DbType="Int")]
		public System.Nullable<int> CURRENCYID
		{
			get
			{
				return this._CURRENCYID;
			}
			set
			{
				if ((this._CURRENCYID != value))
				{
					this.OnCURRENCYIDChanging(value);
					this.SendPropertyChanging();
					this._CURRENCYID = value;
					this.SendPropertyChanged("CURRENCYID");
					this.OnCURRENCYIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CURRENCYRATE", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> CURRENCYRATE
		{
			get
			{
				return this._CURRENCYRATE;
			}
			set
			{
				if ((this._CURRENCYRATE != value))
				{
					this.OnCURRENCYRATEChanging(value);
					this.SendPropertyChanging();
					this._CURRENCYRATE = value;
					this.SendPropertyChanged("CURRENCYRATE");
					this.OnCURRENCYRATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CURRENCYSALESSUM", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> CURRENCYSALESSUM
		{
			get
			{
				return this._CURRENCYSALESSUM;
			}
			set
			{
				if ((this._CURRENCYSALESSUM != value))
				{
					this.OnCURRENCYSALESSUMChanging(value);
					this.SendPropertyChanging();
					this._CURRENCYSALESSUM = value;
					this.SendPropertyChanged("CURRENCYSALESSUM");
					this.OnCURRENCYSALESSUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISCPOLICYID", DbType="Int")]
		public System.Nullable<int> DISCPOLICYID
		{
			get
			{
				return this._DISCPOLICYID;
			}
			set
			{
				if ((this._DISCPOLICYID != value))
				{
					this.OnDISCPOLICYIDChanging(value);
					this.SendPropertyChanging();
					this._DISCPOLICYID = value;
					this.SendPropertyChanged("DISCPOLICYID");
					this.OnDISCPOLICYIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BONUSPOLICYID", DbType="Int")]
		public System.Nullable<int> BONUSPOLICYID
		{
			get
			{
				return this._BONUSPOLICYID;
			}
			set
			{
				if ((this._BONUSPOLICYID != value))
				{
					this.OnBONUSPOLICYIDChanging(value);
					this.SendPropertyChanging();
					this._BONUSPOLICYID = value;
					this.SendPropertyChanged("BONUSPOLICYID");
					this.OnBONUSPOLICYIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OFFERIDFORBONUS", DbType="Int")]
		public System.Nullable<int> OFFERIDFORBONUS
		{
			get
			{
				return this._OFFERIDFORBONUS;
			}
			set
			{
				if ((this._OFFERIDFORBONUS != value))
				{
					this.OnOFFERIDFORBONUSChanging(value);
					this.SendPropertyChanging();
					this._OFFERIDFORBONUS = value;
					this.SendPropertyChanged("OFFERIDFORBONUS");
					this.OnOFFERIDFORBONUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OFFERIDFORDISC", DbType="Int")]
		public System.Nullable<int> OFFERIDFORDISC
		{
			get
			{
				return this._OFFERIDFORDISC;
			}
			set
			{
				if ((this._OFFERIDFORDISC != value))
				{
					this.OnOFFERIDFORDISCChanging(value);
					this.SendPropertyChanging();
					this._OFFERIDFORDISC = value;
					this.SendPropertyChanged("OFFERIDFORDISC");
					this.OnOFFERIDFORDISCChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WORKDAY")]
	public partial class WORKDAY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _WORKDAYID;
		
		private int _SYSTEMID;
		
		private int _SAREAID;
		
		private string _WORKDAYSTART;
		
		private int _CASHIERID;
		
		private short _DELFLAG;
		
		private int _UPDATENUM;
		
		private int _UPDATENUM2;
		
		private EntitySet<SESS> _SESSes;
		
		private EntitySet<ZREP> _ZREPs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnWORKDAYIDChanging(int value);
    partial void OnWORKDAYIDChanged();
    partial void OnSYSTEMIDChanging(int value);
    partial void OnSYSTEMIDChanged();
    partial void OnSAREAIDChanging(int value);
    partial void OnSAREAIDChanged();
    partial void OnWORKDAYSTARTChanging(string value);
    partial void OnWORKDAYSTARTChanged();
    partial void OnCASHIERIDChanging(int value);
    partial void OnCASHIERIDChanged();
    partial void OnDELFLAGChanging(short value);
    partial void OnDELFLAGChanged();
    partial void OnUPDATENUMChanging(int value);
    partial void OnUPDATENUMChanged();
    partial void OnUPDATENUM2Changing(int value);
    partial void OnUPDATENUM2Changed();
    #endregion
		
		public WORKDAY()
		{
			this._SESSes = new EntitySet<SESS>(new Action<SESS>(this.attach_SESSes), new Action<SESS>(this.detach_SESSes));
			this._ZREPs = new EntitySet<ZREP>(new Action<ZREP>(this.attach_ZREPs), new Action<ZREP>(this.detach_ZREPs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WORKDAYID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int WORKDAYID
		{
			get
			{
				return this._WORKDAYID;
			}
			set
			{
				if ((this._WORKDAYID != value))
				{
					this.OnWORKDAYIDChanging(value);
					this.SendPropertyChanging();
					this._WORKDAYID = value;
					this.SendPropertyChanged("WORKDAYID");
					this.OnWORKDAYIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SYSTEMID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SYSTEMID
		{
			get
			{
				return this._SYSTEMID;
			}
			set
			{
				if ((this._SYSTEMID != value))
				{
					this.OnSYSTEMIDChanging(value);
					this.SendPropertyChanging();
					this._SYSTEMID = value;
					this.SendPropertyChanged("SYSTEMID");
					this.OnSYSTEMIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAREAID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SAREAID
		{
			get
			{
				return this._SAREAID;
			}
			set
			{
				if ((this._SAREAID != value))
				{
					this.OnSAREAIDChanging(value);
					this.SendPropertyChanging();
					this._SAREAID = value;
					this.SendPropertyChanged("SAREAID");
					this.OnSAREAIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WORKDAYSTART", DbType="VarChar(14) NOT NULL", CanBeNull=false)]
		public string WORKDAYSTART
		{
			get
			{
				return this._WORKDAYSTART;
			}
			set
			{
				if ((this._WORKDAYSTART != value))
				{
					this.OnWORKDAYSTARTChanging(value);
					this.SendPropertyChanging();
					this._WORKDAYSTART = value;
					this.SendPropertyChanged("WORKDAYSTART");
					this.OnWORKDAYSTARTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CASHIERID", DbType="Int NOT NULL")]
		public int CASHIERID
		{
			get
			{
				return this._CASHIERID;
			}
			set
			{
				if ((this._CASHIERID != value))
				{
					this.OnCASHIERIDChanging(value);
					this.SendPropertyChanging();
					this._CASHIERID = value;
					this.SendPropertyChanged("CASHIERID");
					this.OnCASHIERIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DELFLAG", DbType="SmallInt NOT NULL")]
		public short DELFLAG
		{
			get
			{
				return this._DELFLAG;
			}
			set
			{
				if ((this._DELFLAG != value))
				{
					this.OnDELFLAGChanging(value);
					this.SendPropertyChanging();
					this._DELFLAG = value;
					this.SendPropertyChanged("DELFLAG");
					this.OnDELFLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATENUM", DbType="Int NOT NULL")]
		public int UPDATENUM
		{
			get
			{
				return this._UPDATENUM;
			}
			set
			{
				if ((this._UPDATENUM != value))
				{
					this.OnUPDATENUMChanging(value);
					this.SendPropertyChanging();
					this._UPDATENUM = value;
					this.SendPropertyChanged("UPDATENUM");
					this.OnUPDATENUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATENUM2", DbType="Int NOT NULL")]
		public int UPDATENUM2
		{
			get
			{
				return this._UPDATENUM2;
			}
			set
			{
				if ((this._UPDATENUM2 != value))
				{
					this.OnUPDATENUM2Changing(value);
					this.SendPropertyChanging();
					this._UPDATENUM2 = value;
					this.SendPropertyChanged("UPDATENUM2");
					this.OnUPDATENUM2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="WORKDAY_SESS", Storage="_SESSes", ThisKey="WORKDAYID,SYSTEMID,SAREAID", OtherKey="WORKDAYID,SYSTEMID,SAREAID")]
		public EntitySet<SESS> SESSes
		{
			get
			{
				return this._SESSes;
			}
			set
			{
				this._SESSes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="WORKDAY_ZREP", Storage="_ZREPs", ThisKey="WORKDAYID,SYSTEMID,SAREAID", OtherKey="WORKDAYID,SYSTEMID,SAREAID")]
		public EntitySet<ZREP> ZREPs
		{
			get
			{
				return this._ZREPs;
			}
			set
			{
				this._ZREPs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SESSes(SESS entity)
		{
			this.SendPropertyChanging();
			entity.WORKDAY = this;
		}
		
		private void detach_SESSes(SESS entity)
		{
			this.SendPropertyChanging();
			entity.WORKDAY = null;
		}
		
		private void attach_ZREPs(ZREP entity)
		{
			this.SendPropertyChanging();
			entity.WORKDAY = this;
		}
		
		private void detach_ZREPs(ZREP entity)
		{
			this.SendPropertyChanging();
			entity.WORKDAY = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ZREP")]
	public partial class ZREP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ZREPID;
		
		private int _WORKDAYID;
		
		private int _SYSTEMID;
		
		private int _SAREAID;
		
		private int _CASHIERID;
		
		private string _ZREPFPSN;
		
		private string _ZREPFISCNUM;
		
		private string _ZREPSALES;
		
		private string _ZREPREFS;
		
		private string _ZREPTIME;
		
		private short _DELFLAG;
		
		private int _UPDATENUM;
		
		private int _UPDATENUM2;
		
		private System.Nullable<int> _FIRMID;
		
		private int _SALESCOUNT;
		
		private EntityRef<WORKDAY> _WORKDAY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnZREPIDChanging(int value);
    partial void OnZREPIDChanged();
    partial void OnWORKDAYIDChanging(int value);
    partial void OnWORKDAYIDChanged();
    partial void OnSYSTEMIDChanging(int value);
    partial void OnSYSTEMIDChanged();
    partial void OnSAREAIDChanging(int value);
    partial void OnSAREAIDChanged();
    partial void OnCASHIERIDChanging(int value);
    partial void OnCASHIERIDChanged();
    partial void OnZREPFPSNChanging(string value);
    partial void OnZREPFPSNChanged();
    partial void OnZREPFISCNUMChanging(string value);
    partial void OnZREPFISCNUMChanged();
    partial void OnZREPSALESChanging(string value);
    partial void OnZREPSALESChanged();
    partial void OnZREPREFSChanging(string value);
    partial void OnZREPREFSChanged();
    partial void OnZREPTIMEChanging(string value);
    partial void OnZREPTIMEChanged();
    partial void OnDELFLAGChanging(short value);
    partial void OnDELFLAGChanged();
    partial void OnUPDATENUMChanging(int value);
    partial void OnUPDATENUMChanged();
    partial void OnUPDATENUM2Changing(int value);
    partial void OnUPDATENUM2Changed();
    partial void OnFIRMIDChanging(System.Nullable<int> value);
    partial void OnFIRMIDChanged();
    partial void OnSALESCOUNTChanging(int value);
    partial void OnSALESCOUNTChanged();
    #endregion
		
		public ZREP()
		{
			this._WORKDAY = default(EntityRef<WORKDAY>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZREPID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ZREPID
		{
			get
			{
				return this._ZREPID;
			}
			set
			{
				if ((this._ZREPID != value))
				{
					this.OnZREPIDChanging(value);
					this.SendPropertyChanging();
					this._ZREPID = value;
					this.SendPropertyChanged("ZREPID");
					this.OnZREPIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WORKDAYID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int WORKDAYID
		{
			get
			{
				return this._WORKDAYID;
			}
			set
			{
				if ((this._WORKDAYID != value))
				{
					if (this._WORKDAY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnWORKDAYIDChanging(value);
					this.SendPropertyChanging();
					this._WORKDAYID = value;
					this.SendPropertyChanged("WORKDAYID");
					this.OnWORKDAYIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SYSTEMID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SYSTEMID
		{
			get
			{
				return this._SYSTEMID;
			}
			set
			{
				if ((this._SYSTEMID != value))
				{
					if (this._WORKDAY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSYSTEMIDChanging(value);
					this.SendPropertyChanging();
					this._SYSTEMID = value;
					this.SendPropertyChanged("SYSTEMID");
					this.OnSYSTEMIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAREAID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SAREAID
		{
			get
			{
				return this._SAREAID;
			}
			set
			{
				if ((this._SAREAID != value))
				{
					if (this._WORKDAY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSAREAIDChanging(value);
					this.SendPropertyChanging();
					this._SAREAID = value;
					this.SendPropertyChanged("SAREAID");
					this.OnSAREAIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CASHIERID", DbType="Int NOT NULL")]
		public int CASHIERID
		{
			get
			{
				return this._CASHIERID;
			}
			set
			{
				if ((this._CASHIERID != value))
				{
					this.OnCASHIERIDChanging(value);
					this.SendPropertyChanging();
					this._CASHIERID = value;
					this.SendPropertyChanged("CASHIERID");
					this.OnCASHIERIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZREPFPSN", DbType="NVarChar(50)")]
		public string ZREPFPSN
		{
			get
			{
				return this._ZREPFPSN;
			}
			set
			{
				if ((this._ZREPFPSN != value))
				{
					this.OnZREPFPSNChanging(value);
					this.SendPropertyChanging();
					this._ZREPFPSN = value;
					this.SendPropertyChanged("ZREPFPSN");
					this.OnZREPFPSNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZREPFISCNUM", DbType="NVarChar(50)")]
		public string ZREPFISCNUM
		{
			get
			{
				return this._ZREPFISCNUM;
			}
			set
			{
				if ((this._ZREPFISCNUM != value))
				{
					this.OnZREPFISCNUMChanging(value);
					this.SendPropertyChanging();
					this._ZREPFISCNUM = value;
					this.SendPropertyChanged("ZREPFISCNUM");
					this.OnZREPFISCNUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZREPSALES", DbType="NVarChar(100)")]
		public string ZREPSALES
		{
			get
			{
				return this._ZREPSALES;
			}
			set
			{
				if ((this._ZREPSALES != value))
				{
					this.OnZREPSALESChanging(value);
					this.SendPropertyChanging();
					this._ZREPSALES = value;
					this.SendPropertyChanged("ZREPSALES");
					this.OnZREPSALESChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZREPREFS", DbType="NVarChar(100)")]
		public string ZREPREFS
		{
			get
			{
				return this._ZREPREFS;
			}
			set
			{
				if ((this._ZREPREFS != value))
				{
					this.OnZREPREFSChanging(value);
					this.SendPropertyChanging();
					this._ZREPREFS = value;
					this.SendPropertyChanged("ZREPREFS");
					this.OnZREPREFSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZREPTIME", DbType="VarChar(14) NOT NULL", CanBeNull=false)]
		public string ZREPTIME
		{
			get
			{
				return this._ZREPTIME;
			}
			set
			{
				if ((this._ZREPTIME != value))
				{
					this.OnZREPTIMEChanging(value);
					this.SendPropertyChanging();
					this._ZREPTIME = value;
					this.SendPropertyChanged("ZREPTIME");
					this.OnZREPTIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DELFLAG", DbType="SmallInt NOT NULL")]
		public short DELFLAG
		{
			get
			{
				return this._DELFLAG;
			}
			set
			{
				if ((this._DELFLAG != value))
				{
					this.OnDELFLAGChanging(value);
					this.SendPropertyChanging();
					this._DELFLAG = value;
					this.SendPropertyChanged("DELFLAG");
					this.OnDELFLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATENUM", DbType="Int NOT NULL")]
		public int UPDATENUM
		{
			get
			{
				return this._UPDATENUM;
			}
			set
			{
				if ((this._UPDATENUM != value))
				{
					this.OnUPDATENUMChanging(value);
					this.SendPropertyChanging();
					this._UPDATENUM = value;
					this.SendPropertyChanged("UPDATENUM");
					this.OnUPDATENUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATENUM2", DbType="Int NOT NULL")]
		public int UPDATENUM2
		{
			get
			{
				return this._UPDATENUM2;
			}
			set
			{
				if ((this._UPDATENUM2 != value))
				{
					this.OnUPDATENUM2Changing(value);
					this.SendPropertyChanging();
					this._UPDATENUM2 = value;
					this.SendPropertyChanged("UPDATENUM2");
					this.OnUPDATENUM2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIRMID", DbType="Int")]
		public System.Nullable<int> FIRMID
		{
			get
			{
				return this._FIRMID;
			}
			set
			{
				if ((this._FIRMID != value))
				{
					this.OnFIRMIDChanging(value);
					this.SendPropertyChanging();
					this._FIRMID = value;
					this.SendPropertyChanged("FIRMID");
					this.OnFIRMIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALESCOUNT", DbType="Int NOT NULL")]
		public int SALESCOUNT
		{
			get
			{
				return this._SALESCOUNT;
			}
			set
			{
				if ((this._SALESCOUNT != value))
				{
					this.OnSALESCOUNTChanging(value);
					this.SendPropertyChanging();
					this._SALESCOUNT = value;
					this.SendPropertyChanged("SALESCOUNT");
					this.OnSALESCOUNTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="WORKDAY_ZREP", Storage="_WORKDAY", ThisKey="WORKDAYID,SYSTEMID,SAREAID", OtherKey="WORKDAYID,SYSTEMID,SAREAID", IsForeignKey=true)]
		public WORKDAY WORKDAY
		{
			get
			{
				return this._WORKDAY.Entity;
			}
			set
			{
				WORKDAY previousValue = this._WORKDAY.Entity;
				if (((previousValue != value) 
							|| (this._WORKDAY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._WORKDAY.Entity = null;
						previousValue.ZREPs.Remove(this);
					}
					this._WORKDAY.Entity = value;
					if ((value != null))
					{
						value.ZREPs.Add(this);
						this._WORKDAYID = value.WORKDAYID;
						this._SYSTEMID = value.SYSTEMID;
						this._SAREAID = value.SAREAID;
					}
					else
					{
						this._WORKDAYID = default(int);
						this._SYSTEMID = default(int);
						this._SAREAID = default(int);
					}
					this.SendPropertyChanged("WORKDAY");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CASHIO")]
	public partial class CASHIO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CASHIOID;
		
		private int _SESSID;
		
		private int _SYSTEMID;
		
		private int _SAREAID;
		
		private System.Nullable<int> _TXTBINID;
		
		private System.Nullable<int> _CASHIERID;
		
		private System.Nullable<decimal> _CASHIOSUM;
		
		private System.Nullable<decimal> _CASHIOFINAL;
		
		private short _CASHIOINP;
		
		private string _CASHIOTIME;
		
		private short _DELFLAG;
		
		private int _UPDATENUM;
		
		private int _UPDATENUM2;
		
		private System.Nullable<int> _FIRMID;
		
		private System.Nullable<int> _CURRENCYID;
		
		private System.Nullable<decimal> _CURRENCYRATE;
		
		private System.Nullable<decimal> _CASHIOCURRENCYSUM;
		
		private EntityRef<SESS> _SESS;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCASHIOIDChanging(int value);
    partial void OnCASHIOIDChanged();
    partial void OnSESSIDChanging(int value);
    partial void OnSESSIDChanged();
    partial void OnSYSTEMIDChanging(int value);
    partial void OnSYSTEMIDChanged();
    partial void OnSAREAIDChanging(int value);
    partial void OnSAREAIDChanged();
    partial void OnTXTBINIDChanging(System.Nullable<int> value);
    partial void OnTXTBINIDChanged();
    partial void OnCASHIERIDChanging(System.Nullable<int> value);
    partial void OnCASHIERIDChanged();
    partial void OnCASHIOSUMChanging(System.Nullable<decimal> value);
    partial void OnCASHIOSUMChanged();
    partial void OnCASHIOFINALChanging(System.Nullable<decimal> value);
    partial void OnCASHIOFINALChanged();
    partial void OnCASHIOINPChanging(short value);
    partial void OnCASHIOINPChanged();
    partial void OnCASHIOTIMEChanging(string value);
    partial void OnCASHIOTIMEChanged();
    partial void OnDELFLAGChanging(short value);
    partial void OnDELFLAGChanged();
    partial void OnUPDATENUMChanging(int value);
    partial void OnUPDATENUMChanged();
    partial void OnUPDATENUM2Changing(int value);
    partial void OnUPDATENUM2Changed();
    partial void OnFIRMIDChanging(System.Nullable<int> value);
    partial void OnFIRMIDChanged();
    partial void OnCURRENCYIDChanging(System.Nullable<int> value);
    partial void OnCURRENCYIDChanged();
    partial void OnCURRENCYRATEChanging(System.Nullable<decimal> value);
    partial void OnCURRENCYRATEChanged();
    partial void OnCASHIOCURRENCYSUMChanging(System.Nullable<decimal> value);
    partial void OnCASHIOCURRENCYSUMChanged();
    #endregion
		
		public CASHIO()
		{
			this._SESS = default(EntityRef<SESS>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CASHIOID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CASHIOID
		{
			get
			{
				return this._CASHIOID;
			}
			set
			{
				if ((this._CASHIOID != value))
				{
					this.OnCASHIOIDChanging(value);
					this.SendPropertyChanging();
					this._CASHIOID = value;
					this.SendPropertyChanged("CASHIOID");
					this.OnCASHIOIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SESSID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SESSID
		{
			get
			{
				return this._SESSID;
			}
			set
			{
				if ((this._SESSID != value))
				{
					if (this._SESS.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSESSIDChanging(value);
					this.SendPropertyChanging();
					this._SESSID = value;
					this.SendPropertyChanged("SESSID");
					this.OnSESSIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SYSTEMID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SYSTEMID
		{
			get
			{
				return this._SYSTEMID;
			}
			set
			{
				if ((this._SYSTEMID != value))
				{
					if (this._SESS.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSYSTEMIDChanging(value);
					this.SendPropertyChanging();
					this._SYSTEMID = value;
					this.SendPropertyChanged("SYSTEMID");
					this.OnSYSTEMIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAREAID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SAREAID
		{
			get
			{
				return this._SAREAID;
			}
			set
			{
				if ((this._SAREAID != value))
				{
					if (this._SESS.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSAREAIDChanging(value);
					this.SendPropertyChanging();
					this._SAREAID = value;
					this.SendPropertyChanged("SAREAID");
					this.OnSAREAIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TXTBINID", DbType="Int")]
		public System.Nullable<int> TXTBINID
		{
			get
			{
				return this._TXTBINID;
			}
			set
			{
				if ((this._TXTBINID != value))
				{
					this.OnTXTBINIDChanging(value);
					this.SendPropertyChanging();
					this._TXTBINID = value;
					this.SendPropertyChanged("TXTBINID");
					this.OnTXTBINIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CASHIERID", DbType="Int")]
		public System.Nullable<int> CASHIERID
		{
			get
			{
				return this._CASHIERID;
			}
			set
			{
				if ((this._CASHIERID != value))
				{
					this.OnCASHIERIDChanging(value);
					this.SendPropertyChanging();
					this._CASHIERID = value;
					this.SendPropertyChanged("CASHIERID");
					this.OnCASHIERIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CASHIOSUM", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> CASHIOSUM
		{
			get
			{
				return this._CASHIOSUM;
			}
			set
			{
				if ((this._CASHIOSUM != value))
				{
					this.OnCASHIOSUMChanging(value);
					this.SendPropertyChanging();
					this._CASHIOSUM = value;
					this.SendPropertyChanged("CASHIOSUM");
					this.OnCASHIOSUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CASHIOFINAL", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> CASHIOFINAL
		{
			get
			{
				return this._CASHIOFINAL;
			}
			set
			{
				if ((this._CASHIOFINAL != value))
				{
					this.OnCASHIOFINALChanging(value);
					this.SendPropertyChanging();
					this._CASHIOFINAL = value;
					this.SendPropertyChanged("CASHIOFINAL");
					this.OnCASHIOFINALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CASHIOINP", DbType="SmallInt NOT NULL")]
		public short CASHIOINP
		{
			get
			{
				return this._CASHIOINP;
			}
			set
			{
				if ((this._CASHIOINP != value))
				{
					this.OnCASHIOINPChanging(value);
					this.SendPropertyChanging();
					this._CASHIOINP = value;
					this.SendPropertyChanged("CASHIOINP");
					this.OnCASHIOINPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CASHIOTIME", DbType="VarChar(14)")]
		public string CASHIOTIME
		{
			get
			{
				return this._CASHIOTIME;
			}
			set
			{
				if ((this._CASHIOTIME != value))
				{
					this.OnCASHIOTIMEChanging(value);
					this.SendPropertyChanging();
					this._CASHIOTIME = value;
					this.SendPropertyChanged("CASHIOTIME");
					this.OnCASHIOTIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DELFLAG", DbType="SmallInt NOT NULL")]
		public short DELFLAG
		{
			get
			{
				return this._DELFLAG;
			}
			set
			{
				if ((this._DELFLAG != value))
				{
					this.OnDELFLAGChanging(value);
					this.SendPropertyChanging();
					this._DELFLAG = value;
					this.SendPropertyChanged("DELFLAG");
					this.OnDELFLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATENUM", DbType="Int NOT NULL")]
		public int UPDATENUM
		{
			get
			{
				return this._UPDATENUM;
			}
			set
			{
				if ((this._UPDATENUM != value))
				{
					this.OnUPDATENUMChanging(value);
					this.SendPropertyChanging();
					this._UPDATENUM = value;
					this.SendPropertyChanged("UPDATENUM");
					this.OnUPDATENUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATENUM2", DbType="Int NOT NULL")]
		public int UPDATENUM2
		{
			get
			{
				return this._UPDATENUM2;
			}
			set
			{
				if ((this._UPDATENUM2 != value))
				{
					this.OnUPDATENUM2Changing(value);
					this.SendPropertyChanging();
					this._UPDATENUM2 = value;
					this.SendPropertyChanged("UPDATENUM2");
					this.OnUPDATENUM2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIRMID", DbType="Int")]
		public System.Nullable<int> FIRMID
		{
			get
			{
				return this._FIRMID;
			}
			set
			{
				if ((this._FIRMID != value))
				{
					this.OnFIRMIDChanging(value);
					this.SendPropertyChanging();
					this._FIRMID = value;
					this.SendPropertyChanged("FIRMID");
					this.OnFIRMIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CURRENCYID", DbType="Int")]
		public System.Nullable<int> CURRENCYID
		{
			get
			{
				return this._CURRENCYID;
			}
			set
			{
				if ((this._CURRENCYID != value))
				{
					this.OnCURRENCYIDChanging(value);
					this.SendPropertyChanging();
					this._CURRENCYID = value;
					this.SendPropertyChanged("CURRENCYID");
					this.OnCURRENCYIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CURRENCYRATE", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> CURRENCYRATE
		{
			get
			{
				return this._CURRENCYRATE;
			}
			set
			{
				if ((this._CURRENCYRATE != value))
				{
					this.OnCURRENCYRATEChanging(value);
					this.SendPropertyChanging();
					this._CURRENCYRATE = value;
					this.SendPropertyChanged("CURRENCYRATE");
					this.OnCURRENCYRATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CASHIOCURRENCYSUM", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> CASHIOCURRENCYSUM
		{
			get
			{
				return this._CASHIOCURRENCYSUM;
			}
			set
			{
				if ((this._CASHIOCURRENCYSUM != value))
				{
					this.OnCASHIOCURRENCYSUMChanging(value);
					this.SendPropertyChanging();
					this._CASHIOCURRENCYSUM = value;
					this.SendPropertyChanged("CASHIOCURRENCYSUM");
					this.OnCASHIOCURRENCYSUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SESS_CASHIO", Storage="_SESS", ThisKey="SESSID,SYSTEMID,SAREAID", OtherKey="SESSID,SYSTEMID,SAREAID", IsForeignKey=true)]
		public SESS SESS
		{
			get
			{
				return this._SESS.Entity;
			}
			set
			{
				SESS previousValue = this._SESS.Entity;
				if (((previousValue != value) 
							|| (this._SESS.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SESS.Entity = null;
						previousValue.CASHIOs.Remove(this);
					}
					this._SESS.Entity = value;
					if ((value != null))
					{
						value.CASHIOs.Add(this);
						this._SESSID = value.SESSID;
						this._SYSTEMID = value.SYSTEMID;
						this._SAREAID = value.SAREAID;
					}
					else
					{
						this._SESSID = default(int);
						this._SYSTEMID = default(int);
						this._SAREAID = default(int);
					}
					this.SendPropertyChanged("SESS");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DCARD")]
	public partial class DCARD : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _DCARDID;
		
		private int _CLNTID;
		
		private string _DCARDCODE;
		
		private string _DCARDNAME;
		
		private short _ISPAYMENT;
		
		private short _DELFLAG;
		
		private string _PINCODE;
		
		private int _UPDATENUM;
		
		private short _LOCKED;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDCARDIDChanging(string value);
    partial void OnDCARDIDChanged();
    partial void OnCLNTIDChanging(int value);
    partial void OnCLNTIDChanged();
    partial void OnDCARDCODEChanging(string value);
    partial void OnDCARDCODEChanged();
    partial void OnDCARDNAMEChanging(string value);
    partial void OnDCARDNAMEChanged();
    partial void OnISPAYMENTChanging(short value);
    partial void OnISPAYMENTChanged();
    partial void OnDELFLAGChanging(short value);
    partial void OnDELFLAGChanged();
    partial void OnPINCODEChanging(string value);
    partial void OnPINCODEChanged();
    partial void OnUPDATENUMChanging(int value);
    partial void OnUPDATENUMChanged();
    partial void OnLOCKEDChanging(short value);
    partial void OnLOCKEDChanged();
    #endregion
		
		public DCARD()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DCARDID", DbType="NVarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string DCARDID
		{
			get
			{
				return this._DCARDID;
			}
			set
			{
				if ((this._DCARDID != value))
				{
					this.OnDCARDIDChanging(value);
					this.SendPropertyChanging();
					this._DCARDID = value;
					this.SendPropertyChanged("DCARDID");
					this.OnDCARDIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLNTID", DbType="Int NOT NULL")]
		public int CLNTID
		{
			get
			{
				return this._CLNTID;
			}
			set
			{
				if ((this._CLNTID != value))
				{
					this.OnCLNTIDChanging(value);
					this.SendPropertyChanging();
					this._CLNTID = value;
					this.SendPropertyChanged("CLNTID");
					this.OnCLNTIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DCARDCODE", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string DCARDCODE
		{
			get
			{
				return this._DCARDCODE;
			}
			set
			{
				if ((this._DCARDCODE != value))
				{
					this.OnDCARDCODEChanging(value);
					this.SendPropertyChanging();
					this._DCARDCODE = value;
					this.SendPropertyChanged("DCARDCODE");
					this.OnDCARDCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DCARDNAME", DbType="NVarChar(50)")]
		public string DCARDNAME
		{
			get
			{
				return this._DCARDNAME;
			}
			set
			{
				if ((this._DCARDNAME != value))
				{
					this.OnDCARDNAMEChanging(value);
					this.SendPropertyChanging();
					this._DCARDNAME = value;
					this.SendPropertyChanged("DCARDNAME");
					this.OnDCARDNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISPAYMENT", DbType="SmallInt NOT NULL")]
		public short ISPAYMENT
		{
			get
			{
				return this._ISPAYMENT;
			}
			set
			{
				if ((this._ISPAYMENT != value))
				{
					this.OnISPAYMENTChanging(value);
					this.SendPropertyChanging();
					this._ISPAYMENT = value;
					this.SendPropertyChanged("ISPAYMENT");
					this.OnISPAYMENTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DELFLAG", DbType="SmallInt NOT NULL")]
		public short DELFLAG
		{
			get
			{
				return this._DELFLAG;
			}
			set
			{
				if ((this._DELFLAG != value))
				{
					this.OnDELFLAGChanging(value);
					this.SendPropertyChanging();
					this._DELFLAG = value;
					this.SendPropertyChanged("DELFLAG");
					this.OnDELFLAGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PINCODE", DbType="VarChar(256)")]
		public string PINCODE
		{
			get
			{
				return this._PINCODE;
			}
			set
			{
				if ((this._PINCODE != value))
				{
					this.OnPINCODEChanging(value);
					this.SendPropertyChanging();
					this._PINCODE = value;
					this.SendPropertyChanged("PINCODE");
					this.OnPINCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATENUM", DbType="Int NOT NULL")]
		public int UPDATENUM
		{
			get
			{
				return this._UPDATENUM;
			}
			set
			{
				if ((this._UPDATENUM != value))
				{
					this.OnUPDATENUMChanging(value);
					this.SendPropertyChanging();
					this._UPDATENUM = value;
					this.SendPropertyChanged("UPDATENUM");
					this.OnUPDATENUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOCKED", DbType="SmallInt NOT NULL")]
		public short LOCKED
		{
			get
			{
				return this._LOCKED;
			}
			set
			{
				if ((this._LOCKED != value))
				{
					this.OnLOCKEDChanging(value);
					this.SendPropertyChanging();
					this._LOCKED = value;
					this.SendPropertyChanged("LOCKED");
					this.OnLOCKEDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
