//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CashIn
    {
        public int id { get; set; }
        public long idComInit { get; set; }
        public int FPNumber { get; set; }
        public int InMoney { get; set; }
    }
}
