//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Info
    {
        public long id { get; set; }
        public long DateTime { get; set; }
        public int FPNumber { get; set; }
        public Nullable<System.DateTime> DateTimeOfEndOfShift { get; set; }
        public int Operation { get; set; }
        public Nullable<long> MoneyInBox { get; set; }
        public Nullable<long> SaleCheckNumber { get; set; }
        public Nullable<long> PayCheckNumber { get; set; }
        public Nullable<long> NumZReport { get; set; }
        public Nullable<System.DateTime> LastDateZReport { get; set; }
        public Nullable<long> TurnSaleTax_A { get; set; }
        public Nullable<long> TurnSaleTax_B { get; set; }
        public Nullable<long> TurnSaleTax_C { get; set; }
        public Nullable<long> TurnSaleTax_D { get; set; }
        public Nullable<long> TurnSaleTax_E { get; set; }
        public Nullable<long> TurnSaleTax_F { get; set; }
        public Nullable<long> TurnSaleCard { get; set; }
        public Nullable<long> TurnSaleCredit { get; set; }
        public Nullable<long> TurnSaleCheck { get; set; }
        public Nullable<long> TurnSaleCash { get; set; }
        public Nullable<long> TurnPayTax_A { get; set; }
        public Nullable<long> TurnPayTax_B { get; set; }
        public Nullable<long> TurnPayTax_C { get; set; }
        public Nullable<long> TurnPayTax_D { get; set; }
        public Nullable<long> TurnPayTax_E { get; set; }
        public Nullable<long> TurnPayTax_F { get; set; }
        public Nullable<long> TurnPayCard { get; set; }
        public Nullable<long> TurnPayCredit { get; set; }
        public Nullable<long> TurnPayCheck { get; set; }
        public Nullable<long> TurnPayCash { get; set; }
        public Nullable<long> DiscountSale { get; set; }
        public Nullable<long> ExtraChargeSale { get; set; }
        public Nullable<long> DiscountPay { get; set; }
        public Nullable<long> ExtraChargePay { get; set; }
        public Nullable<long> AvansSum { get; set; }
        public Nullable<long> PaymentSum { get; set; }
        public Nullable<System.DateTime> DateTimeCreate { get; set; }
        public Nullable<System.DateTime> DateTimeUpdate { get; set; }
    }
}
