//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SyncDB
    {
        public long id { get; set; }
        public string CompName { get; set; }
        public int FPNumber { get; set; }
        public string DataServer { get; set; }
        public string DataBaseName { get; set; }
        public int Port { get; set; }
        public string MoxaIP { get; set; }
        public Nullable<int> MoxaPort { get; set; }
        public string TableName { get; set; }
        public System.DateTime DateTimeSyncDB { get; set; }
        public Nullable<System.DateTime> DataAddDateTime { get; set; }
    }
}
