//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Cashiers
    {
        public long id { get; set; }
        public long DATETIME { get; set; }
        public int FPNumber { get; set; }
        public int Operation { get; set; }
        public int Num_Cashier { get; set; }
        public string Name_Cashier { get; set; }
        public int Pass_Cashier { get; set; }
        public bool TakeProgName { get; set; }
        public Nullable<bool> Error { get; set; }
        public Nullable<int> ByteStatus { get; set; }
        public Nullable<int> ByteResult { get; set; }
        public Nullable<int> ByteReserv { get; set; }
    }
}
