//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_exchangeItemsTo
    {
        public long id { get; set; }
        public Nullable<bool> enable { get; set; }
        public string Code { get; set; }
        public string ARTNAME { get; set; }
        public Nullable<int> PackCode { get; set; }
        public Nullable<System.Guid> PackGuid { get; set; }
        public Nullable<int> NalogGroup { get; set; }
        public string NameForCheck { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> coefficient { get; set; }
    }
}
