<?xml version="1.0" encoding="utf-8"?><Database Name="FPWork" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=focus-a;Initial Catalog=FPWork;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="FPWorkConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbl_ComInit" Member="tbl_ComInits">
    <Type Name="tbl_ComInit">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CompName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Port" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Init" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Error" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="WorkOff" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ErrorCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ErrorInfo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FPNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RealNumber" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="SerialNumber" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="FiscalNumber" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="DateTimeBegin" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="DateTimeStop" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="DeltaTime" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="CurrentDate" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="CurrentTime" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="CurrentSystemDateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Version" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="SmenaOpened" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PapStat" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ByteStatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ByteStatusInfo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ByteResult" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ByteResultInfo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ByteReserv" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ByteReservInfo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DataServer" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="DataBaseName" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="MinSumm" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaxSumm" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TypeEvery" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PrintEvery" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KlefMem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateTimeSyncFP" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateTimeSyncDB" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MoxaIP" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="MoxaPort" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>