#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tools
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FPWork")]
	public partial class DataClassesFocusADataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_ComInitDefault(tbl_ComInitDefault instance);
    partial void Updatetbl_ComInitDefault(tbl_ComInitDefault instance);
    partial void Deletetbl_ComInitDefault(tbl_ComInitDefault instance);
    partial void Inserttbl_ComInit(tbl_ComInit instance);
    partial void Updatetbl_ComInit(tbl_ComInit instance);
    partial void Deletetbl_ComInit(tbl_ComInit instance);
    partial void Inserttbl_ART(tbl_ART instance);
    partial void Updatetbl_ART(tbl_ART instance);
    partial void Deletetbl_ART(tbl_ART instance);
    partial void Inserttbl_SALE(tbl_SALE instance);
    partial void Updatetbl_SALE(tbl_SALE instance);
    partial void Deletetbl_SALE(tbl_SALE instance);
    #endregion
		
		public DataClassesFocusADataContext() : 
				base(global::Tools.Properties.Settings.Default.FPWorkConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesFocusADataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesFocusADataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesFocusADataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesFocusADataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_ComInitDefault> tbl_ComInitDefaults
		{
			get
			{
				return this.GetTable<tbl_ComInitDefault>();
			}
		}
		
		public System.Data.Linq.Table<tbl_ComInit> tbl_ComInits
		{
			get
			{
				return this.GetTable<tbl_ComInit>();
			}
		}
		
		public System.Data.Linq.Table<tbl_ART> tbl_ARTs
		{
			get
			{
				return this.GetTable<tbl_ART>();
			}
		}
		
		public System.Data.Linq.Table<tbl_SALE> tbl_SALEs
		{
			get
			{
				return this.GetTable<tbl_SALE>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_ComInitDefault")]
	public partial class tbl_ComInitDefault : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private string _CompName;
		
		private System.Nullable<long> _DateTimeBegin;
		
		private System.Nullable<long> _DateTimeStop;
		
		private System.Nullable<long> _DeltaTime;
		
		private string _DataServer;
		
		private string _DataBaseName;
		
		private System.Nullable<int> _MinSumm;
		
		private System.Nullable<int> _MaxSumm;
		
		private System.Nullable<bool> _TypeEvery;
		
		private System.Nullable<int> _PrintEvery;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnCompNameChanging(string value);
    partial void OnCompNameChanged();
    partial void OnDateTimeBeginChanging(System.Nullable<long> value);
    partial void OnDateTimeBeginChanged();
    partial void OnDateTimeStopChanging(System.Nullable<long> value);
    partial void OnDateTimeStopChanged();
    partial void OnDeltaTimeChanging(System.Nullable<long> value);
    partial void OnDeltaTimeChanged();
    partial void OnDataServerChanging(string value);
    partial void OnDataServerChanged();
    partial void OnDataBaseNameChanging(string value);
    partial void OnDataBaseNameChanged();
    partial void OnMinSummChanging(System.Nullable<int> value);
    partial void OnMinSummChanged();
    partial void OnMaxSummChanging(System.Nullable<int> value);
    partial void OnMaxSummChanged();
    partial void OnTypeEveryChanging(System.Nullable<bool> value);
    partial void OnTypeEveryChanged();
    partial void OnPrintEveryChanging(System.Nullable<int> value);
    partial void OnPrintEveryChanged();
    #endregion
		
		public tbl_ComInitDefault()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompName", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string CompName
		{
			get
			{
				return this._CompName;
			}
			set
			{
				if ((this._CompName != value))
				{
					this.OnCompNameChanging(value);
					this.SendPropertyChanging();
					this._CompName = value;
					this.SendPropertyChanged("CompName");
					this.OnCompNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateTimeBegin", DbType="BigInt")]
		public System.Nullable<long> DateTimeBegin
		{
			get
			{
				return this._DateTimeBegin;
			}
			set
			{
				if ((this._DateTimeBegin != value))
				{
					this.OnDateTimeBeginChanging(value);
					this.SendPropertyChanging();
					this._DateTimeBegin = value;
					this.SendPropertyChanged("DateTimeBegin");
					this.OnDateTimeBeginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateTimeStop", DbType="BigInt")]
		public System.Nullable<long> DateTimeStop
		{
			get
			{
				return this._DateTimeStop;
			}
			set
			{
				if ((this._DateTimeStop != value))
				{
					this.OnDateTimeStopChanging(value);
					this.SendPropertyChanging();
					this._DateTimeStop = value;
					this.SendPropertyChanged("DateTimeStop");
					this.OnDateTimeStopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeltaTime", DbType="BigInt")]
		public System.Nullable<long> DeltaTime
		{
			get
			{
				return this._DeltaTime;
			}
			set
			{
				if ((this._DeltaTime != value))
				{
					this.OnDeltaTimeChanging(value);
					this.SendPropertyChanging();
					this._DeltaTime = value;
					this.SendPropertyChanged("DeltaTime");
					this.OnDeltaTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataServer", DbType="NVarChar(1024)")]
		public string DataServer
		{
			get
			{
				return this._DataServer;
			}
			set
			{
				if ((this._DataServer != value))
				{
					this.OnDataServerChanging(value);
					this.SendPropertyChanging();
					this._DataServer = value;
					this.SendPropertyChanged("DataServer");
					this.OnDataServerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataBaseName", DbType="NVarChar(1024)")]
		public string DataBaseName
		{
			get
			{
				return this._DataBaseName;
			}
			set
			{
				if ((this._DataBaseName != value))
				{
					this.OnDataBaseNameChanging(value);
					this.SendPropertyChanging();
					this._DataBaseName = value;
					this.SendPropertyChanged("DataBaseName");
					this.OnDataBaseNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinSumm", DbType="Int")]
		public System.Nullable<int> MinSumm
		{
			get
			{
				return this._MinSumm;
			}
			set
			{
				if ((this._MinSumm != value))
				{
					this.OnMinSummChanging(value);
					this.SendPropertyChanging();
					this._MinSumm = value;
					this.SendPropertyChanged("MinSumm");
					this.OnMinSummChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxSumm", DbType="Int")]
		public System.Nullable<int> MaxSumm
		{
			get
			{
				return this._MaxSumm;
			}
			set
			{
				if ((this._MaxSumm != value))
				{
					this.OnMaxSummChanging(value);
					this.SendPropertyChanging();
					this._MaxSumm = value;
					this.SendPropertyChanged("MaxSumm");
					this.OnMaxSummChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeEvery", DbType="Bit")]
		public System.Nullable<bool> TypeEvery
		{
			get
			{
				return this._TypeEvery;
			}
			set
			{
				if ((this._TypeEvery != value))
				{
					this.OnTypeEveryChanging(value);
					this.SendPropertyChanging();
					this._TypeEvery = value;
					this.SendPropertyChanged("TypeEvery");
					this.OnTypeEveryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrintEvery", DbType="Int")]
		public System.Nullable<int> PrintEvery
		{
			get
			{
				return this._PrintEvery;
			}
			set
			{
				if ((this._PrintEvery != value))
				{
					this.OnPrintEveryChanging(value);
					this.SendPropertyChanging();
					this._PrintEvery = value;
					this.SendPropertyChanged("PrintEvery");
					this.OnPrintEveryChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_ComInit")]
	public partial class tbl_ComInit : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private string _CompName;
		
		private int _Port;
		
		private bool _Init;
		
		private bool _Error;
		
		private System.Nullable<bool> _WorkOff;
		
		private System.Nullable<bool> _auto;
		
		private System.Nullable<int> _ErrorCode;
		
		private string _ErrorInfo;
		
		private System.Nullable<long> _FPNumber;
		
		private string _RealNumber;
		
		private string _SerialNumber;
		
		private string _FiscalNumber;
		
		private System.Nullable<long> _DateTimeBegin;
		
		private System.Nullable<long> _DateTimeStop;
		
		private System.Nullable<long> _DeltaTime;
		
		private string _CurrentDate;
		
		private string _CurrentTime;
		
		private System.Nullable<System.DateTime> _CurrentSystemDateTime;
		
		private string _Version;
		
		private System.Nullable<bool> _SmenaOpened;
		
		private string _PapStat;
		
		private System.Nullable<int> _ByteStatus;
		
		private string _ByteStatusInfo;
		
		private System.Nullable<int> _ByteResult;
		
		private string _ByteResultInfo;
		
		private System.Nullable<int> _ByteReserv;
		
		private string _ByteReservInfo;
		
		private string _DataServer;
		
		private string _DataBaseName;
		
		private System.Nullable<int> _MinSumm;
		
		private System.Nullable<int> _MaxSumm;
		
		private System.Nullable<bool> _TypeEvery;
		
		private System.Nullable<int> _PrintEvery;
		
		private System.Nullable<int> _KlefMem;
		
		private System.Nullable<System.DateTime> _DateTimeSyncFP;
		
		private System.Nullable<System.DateTime> _DateTimeSyncDB;
		
		private string _MoxaIP;
		
		private System.Nullable<int> _MoxaPort;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnCompNameChanging(string value);
    partial void OnCompNameChanged();
    partial void OnPortChanging(int value);
    partial void OnPortChanged();
    partial void OnInitChanging(bool value);
    partial void OnInitChanged();
    partial void OnErrorChanging(bool value);
    partial void OnErrorChanged();
    partial void OnWorkOffChanging(System.Nullable<bool> value);
    partial void OnWorkOffChanged();
    partial void OnautoChanging(System.Nullable<bool> value);
    partial void OnautoChanged();
    partial void OnErrorCodeChanging(System.Nullable<int> value);
    partial void OnErrorCodeChanged();
    partial void OnErrorInfoChanging(string value);
    partial void OnErrorInfoChanged();
    partial void OnFPNumberChanging(System.Nullable<long> value);
    partial void OnFPNumberChanged();
    partial void OnRealNumberChanging(string value);
    partial void OnRealNumberChanged();
    partial void OnSerialNumberChanging(string value);
    partial void OnSerialNumberChanged();
    partial void OnFiscalNumberChanging(string value);
    partial void OnFiscalNumberChanged();
    partial void OnDateTimeBeginChanging(System.Nullable<long> value);
    partial void OnDateTimeBeginChanged();
    partial void OnDateTimeStopChanging(System.Nullable<long> value);
    partial void OnDateTimeStopChanged();
    partial void OnDeltaTimeChanging(System.Nullable<long> value);
    partial void OnDeltaTimeChanged();
    partial void OnCurrentDateChanging(string value);
    partial void OnCurrentDateChanged();
    partial void OnCurrentTimeChanging(string value);
    partial void OnCurrentTimeChanged();
    partial void OnCurrentSystemDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnCurrentSystemDateTimeChanged();
    partial void OnVersionChanging(string value);
    partial void OnVersionChanged();
    partial void OnSmenaOpenedChanging(System.Nullable<bool> value);
    partial void OnSmenaOpenedChanged();
    partial void OnPapStatChanging(string value);
    partial void OnPapStatChanged();
    partial void OnByteStatusChanging(System.Nullable<int> value);
    partial void OnByteStatusChanged();
    partial void OnByteStatusInfoChanging(string value);
    partial void OnByteStatusInfoChanged();
    partial void OnByteResultChanging(System.Nullable<int> value);
    partial void OnByteResultChanged();
    partial void OnByteResultInfoChanging(string value);
    partial void OnByteResultInfoChanged();
    partial void OnByteReservChanging(System.Nullable<int> value);
    partial void OnByteReservChanged();
    partial void OnByteReservInfoChanging(string value);
    partial void OnByteReservInfoChanged();
    partial void OnDataServerChanging(string value);
    partial void OnDataServerChanged();
    partial void OnDataBaseNameChanging(string value);
    partial void OnDataBaseNameChanged();
    partial void OnMinSummChanging(System.Nullable<int> value);
    partial void OnMinSummChanged();
    partial void OnMaxSummChanging(System.Nullable<int> value);
    partial void OnMaxSummChanged();
    partial void OnTypeEveryChanging(System.Nullable<bool> value);
    partial void OnTypeEveryChanged();
    partial void OnPrintEveryChanging(System.Nullable<int> value);
    partial void OnPrintEveryChanged();
    partial void OnKlefMemChanging(System.Nullable<int> value);
    partial void OnKlefMemChanged();
    partial void OnDateTimeSyncFPChanging(System.Nullable<System.DateTime> value);
    partial void OnDateTimeSyncFPChanged();
    partial void OnDateTimeSyncDBChanging(System.Nullable<System.DateTime> value);
    partial void OnDateTimeSyncDBChanged();
    partial void OnMoxaIPChanging(string value);
    partial void OnMoxaIPChanged();
    partial void OnMoxaPortChanging(System.Nullable<int> value);
    partial void OnMoxaPortChanged();
    #endregion
		
		public tbl_ComInit()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompName", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string CompName
		{
			get
			{
				return this._CompName;
			}
			set
			{
				if ((this._CompName != value))
				{
					this.OnCompNameChanging(value);
					this.SendPropertyChanging();
					this._CompName = value;
					this.SendPropertyChanged("CompName");
					this.OnCompNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Port", DbType="Int NOT NULL")]
		public int Port
		{
			get
			{
				return this._Port;
			}
			set
			{
				if ((this._Port != value))
				{
					this.OnPortChanging(value);
					this.SendPropertyChanging();
					this._Port = value;
					this.SendPropertyChanged("Port");
					this.OnPortChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Init", DbType="Bit NOT NULL")]
		public bool Init
		{
			get
			{
				return this._Init;
			}
			set
			{
				if ((this._Init != value))
				{
					this.OnInitChanging(value);
					this.SendPropertyChanging();
					this._Init = value;
					this.SendPropertyChanged("Init");
					this.OnInitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Error", DbType="Bit NOT NULL")]
		public bool Error
		{
			get
			{
				return this._Error;
			}
			set
			{
				if ((this._Error != value))
				{
					this.OnErrorChanging(value);
					this.SendPropertyChanging();
					this._Error = value;
					this.SendPropertyChanged("Error");
					this.OnErrorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkOff", DbType="Bit")]
		public System.Nullable<bool> WorkOff
		{
			get
			{
				return this._WorkOff;
			}
			set
			{
				if ((this._WorkOff != value))
				{
					this.OnWorkOffChanging(value);
					this.SendPropertyChanging();
					this._WorkOff = value;
					this.SendPropertyChanged("WorkOff");
					this.OnWorkOffChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_auto", DbType="Bit")]
		public System.Nullable<bool> auto
		{
			get
			{
				return this._auto;
			}
			set
			{
				if ((this._auto != value))
				{
					this.OnautoChanging(value);
					this.SendPropertyChanging();
					this._auto = value;
					this.SendPropertyChanged("auto");
					this.OnautoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorCode", DbType="Int")]
		public System.Nullable<int> ErrorCode
		{
			get
			{
				return this._ErrorCode;
			}
			set
			{
				if ((this._ErrorCode != value))
				{
					this.OnErrorCodeChanging(value);
					this.SendPropertyChanging();
					this._ErrorCode = value;
					this.SendPropertyChanged("ErrorCode");
					this.OnErrorCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorInfo", DbType="NVarChar(MAX)")]
		public string ErrorInfo
		{
			get
			{
				return this._ErrorInfo;
			}
			set
			{
				if ((this._ErrorInfo != value))
				{
					this.OnErrorInfoChanging(value);
					this.SendPropertyChanging();
					this._ErrorInfo = value;
					this.SendPropertyChanged("ErrorInfo");
					this.OnErrorInfoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FPNumber", DbType="BigInt")]
		public System.Nullable<long> FPNumber
		{
			get
			{
				return this._FPNumber;
			}
			set
			{
				if ((this._FPNumber != value))
				{
					this.OnFPNumberChanging(value);
					this.SendPropertyChanging();
					this._FPNumber = value;
					this.SendPropertyChanged("FPNumber");
					this.OnFPNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RealNumber", DbType="NVarChar(20)")]
		public string RealNumber
		{
			get
			{
				return this._RealNumber;
			}
			set
			{
				if ((this._RealNumber != value))
				{
					this.OnRealNumberChanging(value);
					this.SendPropertyChanging();
					this._RealNumber = value;
					this.SendPropertyChanged("RealNumber");
					this.OnRealNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SerialNumber", DbType="NVarChar(20)")]
		public string SerialNumber
		{
			get
			{
				return this._SerialNumber;
			}
			set
			{
				if ((this._SerialNumber != value))
				{
					this.OnSerialNumberChanging(value);
					this.SendPropertyChanging();
					this._SerialNumber = value;
					this.SendPropertyChanged("SerialNumber");
					this.OnSerialNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FiscalNumber", DbType="NVarChar(20)")]
		public string FiscalNumber
		{
			get
			{
				return this._FiscalNumber;
			}
			set
			{
				if ((this._FiscalNumber != value))
				{
					this.OnFiscalNumberChanging(value);
					this.SendPropertyChanging();
					this._FiscalNumber = value;
					this.SendPropertyChanged("FiscalNumber");
					this.OnFiscalNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateTimeBegin", DbType="BigInt")]
		public System.Nullable<long> DateTimeBegin
		{
			get
			{
				return this._DateTimeBegin;
			}
			set
			{
				if ((this._DateTimeBegin != value))
				{
					this.OnDateTimeBeginChanging(value);
					this.SendPropertyChanging();
					this._DateTimeBegin = value;
					this.SendPropertyChanged("DateTimeBegin");
					this.OnDateTimeBeginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateTimeStop", DbType="BigInt")]
		public System.Nullable<long> DateTimeStop
		{
			get
			{
				return this._DateTimeStop;
			}
			set
			{
				if ((this._DateTimeStop != value))
				{
					this.OnDateTimeStopChanging(value);
					this.SendPropertyChanging();
					this._DateTimeStop = value;
					this.SendPropertyChanged("DateTimeStop");
					this.OnDateTimeStopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeltaTime", DbType="BigInt")]
		public System.Nullable<long> DeltaTime
		{
			get
			{
				return this._DeltaTime;
			}
			set
			{
				if ((this._DeltaTime != value))
				{
					this.OnDeltaTimeChanging(value);
					this.SendPropertyChanging();
					this._DeltaTime = value;
					this.SendPropertyChanged("DeltaTime");
					this.OnDeltaTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentDate", DbType="NVarChar(10)")]
		public string CurrentDate
		{
			get
			{
				return this._CurrentDate;
			}
			set
			{
				if ((this._CurrentDate != value))
				{
					this.OnCurrentDateChanging(value);
					this.SendPropertyChanging();
					this._CurrentDate = value;
					this.SendPropertyChanged("CurrentDate");
					this.OnCurrentDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentTime", DbType="NVarChar(10)")]
		public string CurrentTime
		{
			get
			{
				return this._CurrentTime;
			}
			set
			{
				if ((this._CurrentTime != value))
				{
					this.OnCurrentTimeChanging(value);
					this.SendPropertyChanging();
					this._CurrentTime = value;
					this.SendPropertyChanged("CurrentTime");
					this.OnCurrentTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentSystemDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> CurrentSystemDateTime
		{
			get
			{
				return this._CurrentSystemDateTime;
			}
			set
			{
				if ((this._CurrentSystemDateTime != value))
				{
					this.OnCurrentSystemDateTimeChanging(value);
					this.SendPropertyChanging();
					this._CurrentSystemDateTime = value;
					this.SendPropertyChanged("CurrentSystemDateTime");
					this.OnCurrentSystemDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Version", DbType="NVarChar(5)")]
		public string Version
		{
			get
			{
				return this._Version;
			}
			set
			{
				if ((this._Version != value))
				{
					this.OnVersionChanging(value);
					this.SendPropertyChanging();
					this._Version = value;
					this.SendPropertyChanged("Version");
					this.OnVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SmenaOpened", DbType="Bit")]
		public System.Nullable<bool> SmenaOpened
		{
			get
			{
				return this._SmenaOpened;
			}
			set
			{
				if ((this._SmenaOpened != value))
				{
					this.OnSmenaOpenedChanging(value);
					this.SendPropertyChanging();
					this._SmenaOpened = value;
					this.SendPropertyChanged("SmenaOpened");
					this.OnSmenaOpenedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PapStat", DbType="NVarChar(MAX)")]
		public string PapStat
		{
			get
			{
				return this._PapStat;
			}
			set
			{
				if ((this._PapStat != value))
				{
					this.OnPapStatChanging(value);
					this.SendPropertyChanging();
					this._PapStat = value;
					this.SendPropertyChanged("PapStat");
					this.OnPapStatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ByteStatus", DbType="Int")]
		public System.Nullable<int> ByteStatus
		{
			get
			{
				return this._ByteStatus;
			}
			set
			{
				if ((this._ByteStatus != value))
				{
					this.OnByteStatusChanging(value);
					this.SendPropertyChanging();
					this._ByteStatus = value;
					this.SendPropertyChanged("ByteStatus");
					this.OnByteStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ByteStatusInfo", DbType="NVarChar(MAX)")]
		public string ByteStatusInfo
		{
			get
			{
				return this._ByteStatusInfo;
			}
			set
			{
				if ((this._ByteStatusInfo != value))
				{
					this.OnByteStatusInfoChanging(value);
					this.SendPropertyChanging();
					this._ByteStatusInfo = value;
					this.SendPropertyChanged("ByteStatusInfo");
					this.OnByteStatusInfoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ByteResult", DbType="Int")]
		public System.Nullable<int> ByteResult
		{
			get
			{
				return this._ByteResult;
			}
			set
			{
				if ((this._ByteResult != value))
				{
					this.OnByteResultChanging(value);
					this.SendPropertyChanging();
					this._ByteResult = value;
					this.SendPropertyChanged("ByteResult");
					this.OnByteResultChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ByteResultInfo", DbType="NVarChar(MAX)")]
		public string ByteResultInfo
		{
			get
			{
				return this._ByteResultInfo;
			}
			set
			{
				if ((this._ByteResultInfo != value))
				{
					this.OnByteResultInfoChanging(value);
					this.SendPropertyChanging();
					this._ByteResultInfo = value;
					this.SendPropertyChanged("ByteResultInfo");
					this.OnByteResultInfoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ByteReserv", DbType="Int")]
		public System.Nullable<int> ByteReserv
		{
			get
			{
				return this._ByteReserv;
			}
			set
			{
				if ((this._ByteReserv != value))
				{
					this.OnByteReservChanging(value);
					this.SendPropertyChanging();
					this._ByteReserv = value;
					this.SendPropertyChanged("ByteReserv");
					this.OnByteReservChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ByteReservInfo", DbType="NVarChar(MAX)")]
		public string ByteReservInfo
		{
			get
			{
				return this._ByteReservInfo;
			}
			set
			{
				if ((this._ByteReservInfo != value))
				{
					this.OnByteReservInfoChanging(value);
					this.SendPropertyChanging();
					this._ByteReservInfo = value;
					this.SendPropertyChanged("ByteReservInfo");
					this.OnByteReservInfoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataServer", DbType="NVarChar(1024)")]
		public string DataServer
		{
			get
			{
				return this._DataServer;
			}
			set
			{
				if ((this._DataServer != value))
				{
					this.OnDataServerChanging(value);
					this.SendPropertyChanging();
					this._DataServer = value;
					this.SendPropertyChanged("DataServer");
					this.OnDataServerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataBaseName", DbType="NVarChar(1024)")]
		public string DataBaseName
		{
			get
			{
				return this._DataBaseName;
			}
			set
			{
				if ((this._DataBaseName != value))
				{
					this.OnDataBaseNameChanging(value);
					this.SendPropertyChanging();
					this._DataBaseName = value;
					this.SendPropertyChanged("DataBaseName");
					this.OnDataBaseNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinSumm", DbType="Int")]
		public System.Nullable<int> MinSumm
		{
			get
			{
				return this._MinSumm;
			}
			set
			{
				if ((this._MinSumm != value))
				{
					this.OnMinSummChanging(value);
					this.SendPropertyChanging();
					this._MinSumm = value;
					this.SendPropertyChanged("MinSumm");
					this.OnMinSummChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxSumm", DbType="Int")]
		public System.Nullable<int> MaxSumm
		{
			get
			{
				return this._MaxSumm;
			}
			set
			{
				if ((this._MaxSumm != value))
				{
					this.OnMaxSummChanging(value);
					this.SendPropertyChanging();
					this._MaxSumm = value;
					this.SendPropertyChanged("MaxSumm");
					this.OnMaxSummChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeEvery", DbType="Bit")]
		public System.Nullable<bool> TypeEvery
		{
			get
			{
				return this._TypeEvery;
			}
			set
			{
				if ((this._TypeEvery != value))
				{
					this.OnTypeEveryChanging(value);
					this.SendPropertyChanging();
					this._TypeEvery = value;
					this.SendPropertyChanged("TypeEvery");
					this.OnTypeEveryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrintEvery", DbType="Int")]
		public System.Nullable<int> PrintEvery
		{
			get
			{
				return this._PrintEvery;
			}
			set
			{
				if ((this._PrintEvery != value))
				{
					this.OnPrintEveryChanging(value);
					this.SendPropertyChanging();
					this._PrintEvery = value;
					this.SendPropertyChanged("PrintEvery");
					this.OnPrintEveryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KlefMem", DbType="Int")]
		public System.Nullable<int> KlefMem
		{
			get
			{
				return this._KlefMem;
			}
			set
			{
				if ((this._KlefMem != value))
				{
					this.OnKlefMemChanging(value);
					this.SendPropertyChanging();
					this._KlefMem = value;
					this.SendPropertyChanged("KlefMem");
					this.OnKlefMemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateTimeSyncFP", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateTimeSyncFP
		{
			get
			{
				return this._DateTimeSyncFP;
			}
			set
			{
				if ((this._DateTimeSyncFP != value))
				{
					this.OnDateTimeSyncFPChanging(value);
					this.SendPropertyChanging();
					this._DateTimeSyncFP = value;
					this.SendPropertyChanged("DateTimeSyncFP");
					this.OnDateTimeSyncFPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateTimeSyncDB", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateTimeSyncDB
		{
			get
			{
				return this._DateTimeSyncDB;
			}
			set
			{
				if ((this._DateTimeSyncDB != value))
				{
					this.OnDateTimeSyncDBChanging(value);
					this.SendPropertyChanging();
					this._DateTimeSyncDB = value;
					this.SendPropertyChanged("DateTimeSyncDB");
					this.OnDateTimeSyncDBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoxaIP", DbType="NVarChar(1024)")]
		public string MoxaIP
		{
			get
			{
				return this._MoxaIP;
			}
			set
			{
				if ((this._MoxaIP != value))
				{
					this.OnMoxaIPChanging(value);
					this.SendPropertyChanging();
					this._MoxaIP = value;
					this.SendPropertyChanged("MoxaIP");
					this.OnMoxaIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoxaPort", DbType="Int")]
		public System.Nullable<int> MoxaPort
		{
			get
			{
				return this._MoxaPort;
			}
			set
			{
				if ((this._MoxaPort != value))
				{
					this.OnMoxaPortChanging(value);
					this.SendPropertyChanging();
					this._MoxaPort = value;
					this.SendPropertyChanged("MoxaPort");
					this.OnMoxaPortChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_ART")]
	public partial class tbl_ART : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private System.Nullable<int> _Code;
		
		private string _ARTNAME;
		
		private System.Nullable<long> _PackCode;
		
		private System.Nullable<System.Guid> _PackGuid;
		
		private System.Nullable<int> _NalogGroup;
		
		private string _NameForCheck;
		
		private long _FPNumber;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnCodeChanging(System.Nullable<int> value);
    partial void OnCodeChanged();
    partial void OnARTNAMEChanging(string value);
    partial void OnARTNAMEChanged();
    partial void OnPackCodeChanging(System.Nullable<long> value);
    partial void OnPackCodeChanged();
    partial void OnPackGuidChanging(System.Nullable<System.Guid> value);
    partial void OnPackGuidChanged();
    partial void OnNalogGroupChanging(System.Nullable<int> value);
    partial void OnNalogGroupChanged();
    partial void OnNameForCheckChanging(string value);
    partial void OnNameForCheckChanged();
    partial void OnFPNumberChanging(long value);
    partial void OnFPNumberChanged();
    #endregion
		
		public tbl_ART()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int")]
		public System.Nullable<int> Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARTNAME", DbType="NVarChar(75)")]
		public string ARTNAME
		{
			get
			{
				return this._ARTNAME;
			}
			set
			{
				if ((this._ARTNAME != value))
				{
					this.OnARTNAMEChanging(value);
					this.SendPropertyChanging();
					this._ARTNAME = value;
					this.SendPropertyChanged("ARTNAME");
					this.OnARTNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PackCode", DbType="BigInt")]
		public System.Nullable<long> PackCode
		{
			get
			{
				return this._PackCode;
			}
			set
			{
				if ((this._PackCode != value))
				{
					this.OnPackCodeChanging(value);
					this.SendPropertyChanging();
					this._PackCode = value;
					this.SendPropertyChanged("PackCode");
					this.OnPackCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PackGuid", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> PackGuid
		{
			get
			{
				return this._PackGuid;
			}
			set
			{
				if ((this._PackGuid != value))
				{
					this.OnPackGuidChanging(value);
					this.SendPropertyChanging();
					this._PackGuid = value;
					this.SendPropertyChanged("PackGuid");
					this.OnPackGuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NalogGroup", DbType="Int")]
		public System.Nullable<int> NalogGroup
		{
			get
			{
				return this._NalogGroup;
			}
			set
			{
				if ((this._NalogGroup != value))
				{
					this.OnNalogGroupChanging(value);
					this.SendPropertyChanging();
					this._NalogGroup = value;
					this.SendPropertyChanged("NalogGroup");
					this.OnNalogGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameForCheck", DbType="NVarChar(75)")]
		public string NameForCheck
		{
			get
			{
				return this._NameForCheck;
			}
			set
			{
				if ((this._NameForCheck != value))
				{
					this.OnNameForCheckChanging(value);
					this.SendPropertyChanging();
					this._NameForCheck = value;
					this.SendPropertyChanged("NameForCheck");
					this.OnNameForCheckChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FPNumber", DbType="BigInt NOT NULL")]
		public long FPNumber
		{
			get
			{
				return this._FPNumber;
			}
			set
			{
				if ((this._FPNumber != value))
				{
					this.OnFPNumberChanging(value);
					this.SendPropertyChanging();
					this._FPNumber = value;
					this.SendPropertyChanged("FPNumber");
					this.OnFPNumberChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_SALES")]
	public partial class tbl_SALE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private System.Nullable<long> _NumPayment;
		
		private long _DATETIME;
		
		private long _FPNumber;
		
		private int _SESSID;
		
		private long _SYSTEMID;
		
		private int _SAREAID;
		
		private long _SORT;
		
		private int _Type;
		
		private string _FRECNUM;
		
		private long _SRECNUM;
		
		private int _Amount;
		
		private int _Amount_Status;
		
		private bool _IsOneQuant;
		
		private int _Price;
		
		private int _NalogGroup;
		
		private bool _MemoryGoodName;
		
		private string _GoodName;
		
		private string _CommentUp;
		
		private string _CommentDown;
		
		private string _StrCode;
		
		private System.Nullable<bool> _Error;
		
		private System.Nullable<int> _ByteStatus;
		
		private System.Nullable<int> _ByteResult;
		
		private System.Nullable<int> _ByteReserv;
		
		private System.Nullable<int> _Old_Price;
		
		private System.Nullable<long> _packname;
		
		private System.Nullable<System.Guid> _PackGuid;
		
		private System.Nullable<int> _RowSum;
		
		private System.Nullable<int> _FPSum;
		
		private System.Nullable<bool> _ForWork;
		
		private System.Nullable<int> _discount;
		
		private System.Nullable<bool> _exchange;
		
		private string _DiscountComment;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnNumPaymentChanging(System.Nullable<long> value);
    partial void OnNumPaymentChanged();
    partial void OnDATETIMEChanging(long value);
    partial void OnDATETIMEChanged();
    partial void OnFPNumberChanging(long value);
    partial void OnFPNumberChanged();
    partial void OnSESSIDChanging(int value);
    partial void OnSESSIDChanged();
    partial void OnSYSTEMIDChanging(long value);
    partial void OnSYSTEMIDChanged();
    partial void OnSAREAIDChanging(int value);
    partial void OnSAREAIDChanged();
    partial void OnSORTChanging(long value);
    partial void OnSORTChanged();
    partial void OnTypeChanging(int value);
    partial void OnTypeChanged();
    partial void OnFRECNUMChanging(string value);
    partial void OnFRECNUMChanged();
    partial void OnSRECNUMChanging(long value);
    partial void OnSRECNUMChanged();
    partial void OnAmountChanging(int value);
    partial void OnAmountChanged();
    partial void OnAmount_StatusChanging(int value);
    partial void OnAmount_StatusChanged();
    partial void OnIsOneQuantChanging(bool value);
    partial void OnIsOneQuantChanged();
    partial void OnPriceChanging(int value);
    partial void OnPriceChanged();
    partial void OnNalogGroupChanging(int value);
    partial void OnNalogGroupChanged();
    partial void OnMemoryGoodNameChanging(bool value);
    partial void OnMemoryGoodNameChanged();
    partial void OnGoodNameChanging(string value);
    partial void OnGoodNameChanged();
    partial void OnCommentUpChanging(string value);
    partial void OnCommentUpChanged();
    partial void OnCommentDownChanging(string value);
    partial void OnCommentDownChanged();
    partial void OnStrCodeChanging(string value);
    partial void OnStrCodeChanged();
    partial void OnErrorChanging(System.Nullable<bool> value);
    partial void OnErrorChanged();
    partial void OnByteStatusChanging(System.Nullable<int> value);
    partial void OnByteStatusChanged();
    partial void OnByteResultChanging(System.Nullable<int> value);
    partial void OnByteResultChanged();
    partial void OnByteReservChanging(System.Nullable<int> value);
    partial void OnByteReservChanged();
    partial void OnOld_PriceChanging(System.Nullable<int> value);
    partial void OnOld_PriceChanged();
    partial void OnpacknameChanging(System.Nullable<long> value);
    partial void OnpacknameChanged();
    partial void OnPackGuidChanging(System.Nullable<System.Guid> value);
    partial void OnPackGuidChanged();
    partial void OnRowSumChanging(System.Nullable<int> value);
    partial void OnRowSumChanged();
    partial void OnFPSumChanging(System.Nullable<int> value);
    partial void OnFPSumChanged();
    partial void OnForWorkChanging(System.Nullable<bool> value);
    partial void OnForWorkChanged();
    partial void OndiscountChanging(System.Nullable<int> value);
    partial void OndiscountChanged();
    partial void OnexchangeChanging(System.Nullable<bool> value);
    partial void OnexchangeChanged();
    partial void OnDiscountCommentChanging(string value);
    partial void OnDiscountCommentChanged();
    #endregion
		
		public tbl_SALE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumPayment", DbType="BigInt")]
		public System.Nullable<long> NumPayment
		{
			get
			{
				return this._NumPayment;
			}
			set
			{
				if ((this._NumPayment != value))
				{
					this.OnNumPaymentChanging(value);
					this.SendPropertyChanging();
					this._NumPayment = value;
					this.SendPropertyChanged("NumPayment");
					this.OnNumPaymentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATETIME", DbType="BigInt NOT NULL")]
		public long DATETIME
		{
			get
			{
				return this._DATETIME;
			}
			set
			{
				if ((this._DATETIME != value))
				{
					this.OnDATETIMEChanging(value);
					this.SendPropertyChanging();
					this._DATETIME = value;
					this.SendPropertyChanged("DATETIME");
					this.OnDATETIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FPNumber", DbType="BigInt NOT NULL")]
		public long FPNumber
		{
			get
			{
				return this._FPNumber;
			}
			set
			{
				if ((this._FPNumber != value))
				{
					this.OnFPNumberChanging(value);
					this.SendPropertyChanging();
					this._FPNumber = value;
					this.SendPropertyChanged("FPNumber");
					this.OnFPNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SESSID", DbType="Int NOT NULL")]
		public int SESSID
		{
			get
			{
				return this._SESSID;
			}
			set
			{
				if ((this._SESSID != value))
				{
					this.OnSESSIDChanging(value);
					this.SendPropertyChanging();
					this._SESSID = value;
					this.SendPropertyChanged("SESSID");
					this.OnSESSIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SYSTEMID", DbType="BigInt NOT NULL")]
		public long SYSTEMID
		{
			get
			{
				return this._SYSTEMID;
			}
			set
			{
				if ((this._SYSTEMID != value))
				{
					this.OnSYSTEMIDChanging(value);
					this.SendPropertyChanging();
					this._SYSTEMID = value;
					this.SendPropertyChanged("SYSTEMID");
					this.OnSYSTEMIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAREAID", DbType="Int NOT NULL")]
		public int SAREAID
		{
			get
			{
				return this._SAREAID;
			}
			set
			{
				if ((this._SAREAID != value))
				{
					this.OnSAREAIDChanging(value);
					this.SendPropertyChanging();
					this._SAREAID = value;
					this.SendPropertyChanged("SAREAID");
					this.OnSAREAIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SORT", DbType="BigInt NOT NULL")]
		public long SORT
		{
			get
			{
				return this._SORT;
			}
			set
			{
				if ((this._SORT != value))
				{
					this.OnSORTChanging(value);
					this.SendPropertyChanging();
					this._SORT = value;
					this.SendPropertyChanged("SORT");
					this.OnSORTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="Int NOT NULL")]
		public int Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FRECNUM", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string FRECNUM
		{
			get
			{
				return this._FRECNUM;
			}
			set
			{
				if ((this._FRECNUM != value))
				{
					this.OnFRECNUMChanging(value);
					this.SendPropertyChanging();
					this._FRECNUM = value;
					this.SendPropertyChanged("FRECNUM");
					this.OnFRECNUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SRECNUM", DbType="BigInt NOT NULL")]
		public long SRECNUM
		{
			get
			{
				return this._SRECNUM;
			}
			set
			{
				if ((this._SRECNUM != value))
				{
					this.OnSRECNUMChanging(value);
					this.SendPropertyChanging();
					this._SRECNUM = value;
					this.SendPropertyChanged("SRECNUM");
					this.OnSRECNUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Int NOT NULL")]
		public int Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this.OnAmountChanging(value);
					this.SendPropertyChanging();
					this._Amount = value;
					this.SendPropertyChanged("Amount");
					this.OnAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount_Status", DbType="Int NOT NULL")]
		public int Amount_Status
		{
			get
			{
				return this._Amount_Status;
			}
			set
			{
				if ((this._Amount_Status != value))
				{
					this.OnAmount_StatusChanging(value);
					this.SendPropertyChanging();
					this._Amount_Status = value;
					this.SendPropertyChanged("Amount_Status");
					this.OnAmount_StatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsOneQuant", DbType="Bit NOT NULL")]
		public bool IsOneQuant
		{
			get
			{
				return this._IsOneQuant;
			}
			set
			{
				if ((this._IsOneQuant != value))
				{
					this.OnIsOneQuantChanging(value);
					this.SendPropertyChanging();
					this._IsOneQuant = value;
					this.SendPropertyChanged("IsOneQuant");
					this.OnIsOneQuantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Int NOT NULL")]
		public int Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this.OnPriceChanging(value);
					this.SendPropertyChanging();
					this._Price = value;
					this.SendPropertyChanged("Price");
					this.OnPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NalogGroup", DbType="Int NOT NULL")]
		public int NalogGroup
		{
			get
			{
				return this._NalogGroup;
			}
			set
			{
				if ((this._NalogGroup != value))
				{
					this.OnNalogGroupChanging(value);
					this.SendPropertyChanging();
					this._NalogGroup = value;
					this.SendPropertyChanged("NalogGroup");
					this.OnNalogGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemoryGoodName", DbType="Bit NOT NULL")]
		public bool MemoryGoodName
		{
			get
			{
				return this._MemoryGoodName;
			}
			set
			{
				if ((this._MemoryGoodName != value))
				{
					this.OnMemoryGoodNameChanging(value);
					this.SendPropertyChanging();
					this._MemoryGoodName = value;
					this.SendPropertyChanged("MemoryGoodName");
					this.OnMemoryGoodNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoodName", DbType="NVarChar(75) NOT NULL", CanBeNull=false)]
		public string GoodName
		{
			get
			{
				return this._GoodName;
			}
			set
			{
				if ((this._GoodName != value))
				{
					this.OnGoodNameChanging(value);
					this.SendPropertyChanging();
					this._GoodName = value;
					this.SendPropertyChanged("GoodName");
					this.OnGoodNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommentUp", DbType="NVarChar(27)")]
		public string CommentUp
		{
			get
			{
				return this._CommentUp;
			}
			set
			{
				if ((this._CommentUp != value))
				{
					this.OnCommentUpChanging(value);
					this.SendPropertyChanging();
					this._CommentUp = value;
					this.SendPropertyChanged("CommentUp");
					this.OnCommentUpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommentDown", DbType="NVarChar(27)")]
		public string CommentDown
		{
			get
			{
				return this._CommentDown;
			}
			set
			{
				if ((this._CommentDown != value))
				{
					this.OnCommentDownChanging(value);
					this.SendPropertyChanging();
					this._CommentDown = value;
					this.SendPropertyChanged("CommentDown");
					this.OnCommentDownChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StrCode", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string StrCode
		{
			get
			{
				return this._StrCode;
			}
			set
			{
				if ((this._StrCode != value))
				{
					this.OnStrCodeChanging(value);
					this.SendPropertyChanging();
					this._StrCode = value;
					this.SendPropertyChanged("StrCode");
					this.OnStrCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Error", DbType="Bit")]
		public System.Nullable<bool> Error
		{
			get
			{
				return this._Error;
			}
			set
			{
				if ((this._Error != value))
				{
					this.OnErrorChanging(value);
					this.SendPropertyChanging();
					this._Error = value;
					this.SendPropertyChanged("Error");
					this.OnErrorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ByteStatus", DbType="Int")]
		public System.Nullable<int> ByteStatus
		{
			get
			{
				return this._ByteStatus;
			}
			set
			{
				if ((this._ByteStatus != value))
				{
					this.OnByteStatusChanging(value);
					this.SendPropertyChanging();
					this._ByteStatus = value;
					this.SendPropertyChanged("ByteStatus");
					this.OnByteStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ByteResult", DbType="Int")]
		public System.Nullable<int> ByteResult
		{
			get
			{
				return this._ByteResult;
			}
			set
			{
				if ((this._ByteResult != value))
				{
					this.OnByteResultChanging(value);
					this.SendPropertyChanging();
					this._ByteResult = value;
					this.SendPropertyChanged("ByteResult");
					this.OnByteResultChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ByteReserv", DbType="Int")]
		public System.Nullable<int> ByteReserv
		{
			get
			{
				return this._ByteReserv;
			}
			set
			{
				if ((this._ByteReserv != value))
				{
					this.OnByteReservChanging(value);
					this.SendPropertyChanging();
					this._ByteReserv = value;
					this.SendPropertyChanged("ByteReserv");
					this.OnByteReservChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Old_Price", DbType="Int")]
		public System.Nullable<int> Old_Price
		{
			get
			{
				return this._Old_Price;
			}
			set
			{
				if ((this._Old_Price != value))
				{
					this.OnOld_PriceChanging(value);
					this.SendPropertyChanging();
					this._Old_Price = value;
					this.SendPropertyChanged("Old_Price");
					this.OnOld_PriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_packname", DbType="BigInt")]
		public System.Nullable<long> packname
		{
			get
			{
				return this._packname;
			}
			set
			{
				if ((this._packname != value))
				{
					this.OnpacknameChanging(value);
					this.SendPropertyChanging();
					this._packname = value;
					this.SendPropertyChanged("packname");
					this.OnpacknameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PackGuid", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> PackGuid
		{
			get
			{
				return this._PackGuid;
			}
			set
			{
				if ((this._PackGuid != value))
				{
					this.OnPackGuidChanging(value);
					this.SendPropertyChanging();
					this._PackGuid = value;
					this.SendPropertyChanged("PackGuid");
					this.OnPackGuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowSum", DbType="Int")]
		public System.Nullable<int> RowSum
		{
			get
			{
				return this._RowSum;
			}
			set
			{
				if ((this._RowSum != value))
				{
					this.OnRowSumChanging(value);
					this.SendPropertyChanging();
					this._RowSum = value;
					this.SendPropertyChanged("RowSum");
					this.OnRowSumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FPSum", DbType="Int")]
		public System.Nullable<int> FPSum
		{
			get
			{
				return this._FPSum;
			}
			set
			{
				if ((this._FPSum != value))
				{
					this.OnFPSumChanging(value);
					this.SendPropertyChanging();
					this._FPSum = value;
					this.SendPropertyChanged("FPSum");
					this.OnFPSumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ForWork", DbType="Bit")]
		public System.Nullable<bool> ForWork
		{
			get
			{
				return this._ForWork;
			}
			set
			{
				if ((this._ForWork != value))
				{
					this.OnForWorkChanging(value);
					this.SendPropertyChanging();
					this._ForWork = value;
					this.SendPropertyChanged("ForWork");
					this.OnForWorkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_discount", DbType="Int")]
		public System.Nullable<int> discount
		{
			get
			{
				return this._discount;
			}
			set
			{
				if ((this._discount != value))
				{
					this.OndiscountChanging(value);
					this.SendPropertyChanging();
					this._discount = value;
					this.SendPropertyChanged("discount");
					this.OndiscountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exchange", DbType="Bit")]
		public System.Nullable<bool> exchange
		{
			get
			{
				return this._exchange;
			}
			set
			{
				if ((this._exchange != value))
				{
					this.OnexchangeChanging(value);
					this.SendPropertyChanging();
					this._exchange = value;
					this.SendPropertyChanged("exchange");
					this.OnexchangeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiscountComment", DbType="NVarChar(25)")]
		public string DiscountComment
		{
			get
			{
				return this._DiscountComment;
			}
			set
			{
				if ((this._DiscountComment != value))
				{
					this.OnDiscountCommentChanging(value);
					this.SendPropertyChanging();
					this._DiscountComment = value;
					this.SendPropertyChanged("DiscountComment");
					this.OnDiscountCommentChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
